// Generated by owner_codegen.cpp; do not edit.
#pragma once
#include "symphony/knowledge/engine/operation.hpp"
namespace symphony::snv::scnv::interface {
namespace engine = symphony::knowledge::engine;
inline constexpr auto version = "0.1.0-dev";
inline std::vector<engine::OperationSpec> interface_operations() { return {
  {"engop:symphony:scnv.names-validate", "names_validate", "implemented", false, true, {"ssfv:symphony:scnv-engine"}, {"inspect","validate","propose"}, "qxctl_required", "scnv.names.v1", "scnv.names-result.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:scnv.names-resolve", "names_resolve", "implemented", false, true, {"ssfv:symphony:scnv-engine"}, {"inspect","query"}, "qxctl_required", "scnv.resolve.v1", "scnv.resolve-result.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
}; }
}
