// Generated by owner_codegen.cpp; do not edit.
#pragma once
#include "symphony/knowledge/engine/operation.hpp"
namespace symphony::snv::sciv::interface {
namespace engine = symphony::knowledge::engine;
inline constexpr auto version = "0.1.0-dev";
inline std::vector<engine::OperationSpec> interface_operations() { return {
  {"engop:symphony:sciv.sciv-validate", "sciv_validate", "implemented", false, true, {"ssfv:symphony:sciv-engine"}, {"validate","inspect"}, "qxctl_required", "symphony.snv.sciv.evidence.v1", "symphony.snv.sciv.result.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:sciv.sciv-transition", "sciv_transition", "implemented", false, true, {"ssfv:symphony:sciv-engine"}, {"propose"}, "qxctl_required", "symphony.snv.sciv.transition.v1", "symphony.snv.sciv.transition-result.v1", "proposal_only", "idempotent", true, "none", "", "supported", "freezing"},
}; }
}
