// Generated by tools/shv-interface-codegen/generate.py; do not edit.
#pragma once
#include <array>
#include <vector>
#include <string>
namespace symphony::knowledge::shv_publication {
inline constexpr auto version = "0.3.0-dev";
struct InterfaceOperation { const char *id; const char *name; const char *input; const char *output; std::vector<std::string> interactions; bool expected_state; };
inline const std::array<InterfaceOperation, 4> interface_operations = {{
  {"engop:symphony:shv-publication.inspect", "inspect", "symphony.shv.inspect-input.v1", "symphony.knowledge.engine-descriptor.v2", {"inspect"}, false},
  {"engop:symphony:shv-publication.publication.plan", "publication_plan", "symphony.shv.publication-plan-input.v1", "symphony.shv.publication-plan.v1", {"propose"}, false},
  {"engop:symphony:shv-publication.publication.reduce", "publication_reduce", "symphony.shv.publication-reduce-input.v1", "symphony.shv.publication-transition.v1", {"apply", "recover"}, false},
  {"engop:symphony:shv-publication.publication.status", "publication_status", "symphony.shv.publication-status-input.v1", "symphony.shv.publication-status.v1", {"inspect"}, false},
}};
}
