// Generated by owner_codegen.cpp; do not edit.
#pragma once
#include "symphony/knowledge/engine/operation.hpp"
namespace symphony::snv::snrv::interface {
namespace engine = symphony::knowledge::engine;
inline constexpr auto version = "0.1.0-dev";
inline std::vector<engine::OperationSpec> interface_operations() { return {
  {"engop:symphony:snrv.resources-validate", "resources_validate", "implemented", false, true, {"ssfv:symphony:snrv-engine"}, {"validate","propose"}, "qxctl_required", "symphony.snrv.resources-validate-input.v1", "symphony.snrv.resources-validate.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
}; }
}
