"""Independent wire examples. No expected rows generated by native projection."""
import argparse, copy, hashlib, json, os, stat, subprocess, time
from pathlib import Path
p=argparse.ArgumentParser(); selected=p.add_mutually_exclusive_group(required=True); selected.add_argument('--engine'); selected.add_argument('--prefix'); args=p.parse_args()
def canonical(x): return json.dumps(x,sort_keys=True,separators=(',',':'),ensure_ascii=False).encode()
def seal(x,key='digest'):
 x=copy.deepcopy(x); x.pop(key,None); x[key]='sha256:'+hashlib.sha256(canonical(x)).hexdigest(); return x
def call(op,payload,good=True,raw=None):
 req={'protocol':'symphony.knowledge.engine-process.v1','request_id':'conformance','correlation_id':'conformance','operation':op,'target_engine':'symphony-shv-graph-adapter','deadline_unix_ms':int(time.time()*1000)+30000,'payload':payload}
 r=subprocess.run([args.engine],input=canonical(req) if raw is None else raw,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
 out=json.loads(r.stdout); assert not r.stderr
 assert out==seal(out,'response_digest'),out
 assert (r.returncode==0)==good,(r.returncode,out)
 assert out['outcome']==('ok' if good else 'error'),out
 return out.get('result')
def test_adapter_conformance():
 artifact=seal({'protocol':'example.independent-owner.v1','literal':{'x':'λ\\u2028\u2028','large':9007199254740991,'decimal':'1.25'}})
 graph=seal({'protocol':'symphony.graph.exchange.v1','owner':{'engine_id':'example-owner','engine_version':'exact.7','artifact_protocol':artifact['protocol'],'artifact_digest':artifact['digest']},'owner_artifact':artifact,'nodes':[{'id':'a','labels':['arbitrary'],'properties':{'nested':[None,False,{'label':'😀'}]}},{'id':'b','labels':[],'properties':{'keep':-7}}],'edges':[{'id':'edge','from':'a','to':'b','label':'custom','properties':{'opaque':{'never_execute':'rm -rf /'}}}]})
 result=call('roundtrip',{'graph':graph}); assert result==seal({'protocol':'symphony.graph.adapter-result.v1','backend':'portable-reference','operation':'roundtrip','graph':graph})
 result=call('query',{'graph':graph,'kind':'nodes','ids':['missing','b','a']}); assert result==seal({'protocol':'symphony.graph.adapter-result.v1','backend':'portable-reference','operation':'query','graph_digest':graph['digest'],'kind':'nodes','ids':['missing','b','a'],'rows':graph['nodes'],'missing_ids':['missing']})
 assert call('query',{'graph':graph,'kind':'edges','ids':[]})['rows']==graph['edges']
 assert call('roundtrip',{'graph':graph})['graph']==graph
 for label,change in [
  ('dangling',lambda g:g['edges'][0].update(to='absent')),
  ('duplicate_node',lambda g:g['nodes'].append(copy.deepcopy(g['nodes'][1]))),
  ('unsorted_node',lambda g:g['nodes'].reverse()),
  ('duplicate_edge',lambda g:g['edges'].append(copy.deepcopy(g['edges'][0]))),
  ('duplicate_label',lambda g:g['nodes'][0].update(labels=['x','x'])),
  ('unsorted_label',lambda g:g['nodes'][0].update(labels=['z','a'])),
  ('owner_mismatch',lambda g:g['owner'].update(artifact_protocol='wrong')),
  ('artifact_tamper',lambda g:g['owner_artifact'].update(literal='tampered')),
  ('unknown_graph_field',lambda g:g.update(extra=1)),
  ('unknown_node_field',lambda g:g['nodes'][0].update(extra=1)),
  ('wrong_properties',lambda g:g['nodes'][0].update(properties=[])),
  ('float_value',lambda g:g['nodes'][0].update(properties={'x':0.1})),
  ('large_integer',lambda g:g['nodes'][0].update(properties={'x':9007199254740992})),
  ('oversized_string',lambda g:g['nodes'][0].update(properties={'x':'x'*65537})),
 ]:
  changed=copy.deepcopy(graph); change(changed); call('roundtrip',{'graph':seal(changed)},False)
 call('roundtrip',{'graph':dict(graph,digest='sha256:'+'0'*64)},False)
 call('query',{'graph':graph,'kind':'nodes','ids':['a','a']},False)
 call('query',{'graph':graph,'kind':'sql','ids':[]},False)
 call('roundtrip',{'graph':graph,'extra':True},False)
 call('unsupported',{},False)
 call('inspect',{'extra':True},False)
 descriptor=call('inspect',{}); assert descriptor==seal(descriptor,'descriptor_digest')
 assert {x['operation_name'] for x in descriptor['operations']}=={'inspect','roundtrip','query'}
 assert descriptor['canonical_apply_enabled'] is False and descriptor['network_listener'] is False
 print('PASS: independent roundtrip/query, Unicode/integer preservation, 20 negative structural/process cases, exact descriptor')

def receipt_read(root, relative, maximum):
 parts=Path(root).parts
 assert Path(root).is_absolute() and '..' not in parts
 fd=os.open('/',os.O_RDONLY|os.O_DIRECTORY|os.O_NOFOLLOW)
 try:
  for part in list(parts[1:])+list(Path(relative).parts[:-1]):
   assert part not in ('','.','..')
   nxt=os.open(part,os.O_RDONLY|os.O_DIRECTORY|os.O_NOFOLLOW,dir_fd=fd);os.close(fd);fd=nxt
  leaf=os.open(Path(relative).name,os.O_RDONLY|os.O_NOFOLLOW,dir_fd=fd)
  try:
   info=os.fstat(leaf);assert stat.S_ISREG(info.st_mode) and info.st_size<=maximum
   data=b''
   while True:
    block=os.read(leaf,65536)
    if not block:break
    data+=block;assert len(data)<=maximum
   return data,info
  finally:os.close(leaf)
 finally:os.close(fd)

def installed_engine(prefix):
 root=Path(prefix).absolute();module='shv-graph-adapter';engine='symphony-shv-graph-adapter';version='0.1.0-dev'
 receipt_path=f'share/symphony/receipts/{module}/{version}/install-receipt.json'
 raw,_=receipt_read(root,receipt_path,1048576);receipt=json.loads(raw)
 assert receipt==seal(receipt,'receipt_digest')
 for key,value in {'protocol':'symphony.knowledge.install-receipt.v2','format_version':2,'component_id':module,'module_id':module,'package_id':module,'engine_id':engine,'vector_id':'shv','version':version,'component_kind':'adapter'}.items():assert receipt[key]==value,(key,receipt[key])
 relative=f'libexec/symphony/{module}/{version}/{engine}'
 entries=[e for e in receipt['entry_points'] if e['entry_point_id']==engine]
 assert len(entries)==1 and entries[0]['path']==relative and entries[0]['kind']=='executable' and entries[0]['protocols']==['symphony.knowledge.engine-process.v1']
 owned=[f for f in receipt['files'] if f['path']==relative];assert len(owned)==1 and owned[0]['kind']=='executable'
 binary,info=receipt_read(root,relative,4194304);assert info.st_mode & 0o111 and len(binary)==owned[0]['size'] and 'sha256:'+hashlib.sha256(binary).hexdigest()==owned[0]['digest']
 return str(root/relative)

def test_installed_process(prefix):
 args.engine=installed_engine(prefix)
 test_adapter_conformance()
 print('PASS: executed exact receipt-owned installed entry point after no-follow identity/size/digest verification')

if __name__=='__main__':
 if args.prefix:test_installed_process(args.prefix)
 else:test_adapter_conformance()
