// Generated by owner_codegen.cpp; do not edit.
#pragma once
#include "symphony/knowledge/engine/operation.hpp"
namespace symphony::shv::duckdb_connector {
namespace engine = symphony::knowledge::engine;
inline constexpr auto version = "0.4.0-dev";
inline std::vector<engine::OperationSpec> interface_operations() { return {
  {"engop:symphony:shv.graph-store.inspect", "inspect", "implemented", false, true, {"ssfv:symphony:shv-graph-duckdb-connector"}, {"inspect"}, "qxctl_required", "symphony.shv.graph-store-inspect-input.v1", "symphony.knowledge.engine-descriptor.v2", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:shv.graph-store.prepare", "prepare", "implemented", false, true, {"ssfv:symphony:shv-graph-duckdb-connector"}, {"invoke"}, "qxctl_required", "symphony.shv.graph-store-prepare-input.v1", "symphony.shv.graph-store-status.v1", "evidence_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:shv.graph-store.commit", "commit", "implemented", false, true, {"ssfv:symphony:shv-graph-duckdb-connector"}, {"invoke","recover"}, "qxctl_required", "symphony.shv.graph-store-commit-input.v1", "symphony.shv.graph-store-status.v1", "evidence_only", "idempotent", true, "none", "", "supported", "freezing"},
  {"engop:symphony:shv.graph-store.status", "status", "implemented", false, true, {"ssfv:symphony:shv-graph-duckdb-connector"}, {"inspect","recover"}, "qxctl_required", "symphony.shv.graph-store-status-input.v1", "symphony.shv.graph-store-status.v1", "evidence_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:shv.graph-store.query", "query", "implemented", false, true, {"ssfv:symphony:shv-graph-duckdb-connector"}, {"query"}, "qxctl_required", "symphony.shv.graph-store-query-input.v1", "symphony.shv.graph-store-query.v1", "evidence_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:shv.graph-store.export", "export", "implemented", false, true, {"ssfv:symphony:shv-graph-duckdb-connector"}, {"query"}, "qxctl_required", "symphony.shv.graph-store-export-input.v1", "symphony.shv.graph-store-export.v1", "evidence_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:shv.graph-store.inventory", "inventory", "implemented", false, true, {"ssfv:symphony:shv-graph-duckdb-connector"}, {"query"}, "qxctl_required", "symphony.shv.graph-store-inventory-input.v1", "symphony.shv.graph-store-inventory.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:shv.graph-store.transfer.plan", "transfer_plan", "implemented", false, true, {"ssfv:symphony:shv-graph-duckdb-connector"}, {"query"}, "qxctl_required", "symphony.shv.graph-store-transfer_plan-input.v1", "symphony.shv.graph-store-transfer-plan.v1", "read_only", "idempotent", true, "none", "", "supported", "freezing"},
}; }
}
