// Generated by owner_codegen.py; do not edit.
#pragma once
#include "symphony/knowledge/engine/operation.hpp"
namespace symphony::knowledge::shv {
namespace engine = symphony::knowledge::engine;
#ifdef SYMPHONY_SHV_KERNEL_EMBEDDED_PREVIOUS
inline constexpr auto version = "0.3.0-dev";
#else
inline constexpr auto version = "0.4.0-dev";
#endif
inline std::vector<engine::OperationSpec> interface_operations() { return {
  {"engop:symphony:shv.inspect", "inspect", "implemented", false, true, {"ssfv:symphony:shv-engine"}, {"inspect"}, "qxctl_required", "symphony.shv.inspect-input.v1", "symphony.knowledge.engine-descriptor.v2", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:shv.coverage.default", "coverage_default", "implemented", false, true, {"ssfv:symphony:shv-engine"}, {"invoke"}, "qxctl_required", "symphony.shv.coverage-default-input.v1", "symphony.shv.coverage-profile.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:shv.coverage.plan", "coverage_plan", "implemented", false, true, {"ssfv:symphony:shv-engine"}, {"invoke"}, "qxctl_required", "symphony.shv.coverage-plan-input.v1", "symphony.shv.coverage-result.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:shv.catalogue.build", "catalogue_build", "implemented", false, true, {"ssfv:symphony:shv-engine"}, {"invoke"}, "qxctl_required", "symphony.shv.catalogue-build-input.v1", "symphony.shv.catalogue.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:shv.catalogue.query", "catalogue_query", "implemented", false, true, {"ssfv:symphony:shv-engine"}, {"query"}, "qxctl_required", "symphony.shv.catalogue-query-input.v1", "symphony.shv.query-result.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:shv.evaluate", "evaluate", "implemented", false, true, {"ssfv:symphony:shv-engine"}, {"invoke"}, "qxctl_required", "symphony.shv.evaluate-input.v1", "symphony.shv.evaluation.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:shv.graph.project", "graph_project", "implemented", false, true, {"ssfv:symphony:shv-engine"}, {"invoke"}, "qxctl_required", "symphony.shv.graph-project-input.v1", "symphony.graph.exchange.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:shv.graph.validate", "graph_validate", "implemented", false, true, {"ssfv:symphony:shv-engine"}, {"invoke"}, "qxctl_required", "symphony.shv.graph-validate-input.v1", "symphony.shv.graph-validation.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
}; }
}
