// Generated by owner_codegen.cpp; do not edit.
#pragma once
#include "symphony/knowledge/engine/operation.hpp"
namespace symphony::snv::snv::interface {
namespace engine = symphony::knowledge::engine;
inline constexpr auto version = "0.1.0-dev";
inline std::vector<engine::OperationSpec> interface_operations() { return {
  {"engop:symphony:snv.snv-inspect", "snv_inspect", "implemented", false, true, {"ssfv:symphony:snv-engine"}, {"inspect","query"}, "qxctl_required", "symphony.snv.inspect-input.v1", "symphony.snv.inspect.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:snv.snv-evidence-plan", "snv_evidence_plan", "implemented", false, true, {"ssfv:symphony:snv-engine"}, {"propose"}, "qxctl_required", "symphony.snv.evidence-plan-input.v1", "symphony.snv.evidence-plan.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:snv.snv-state-plan", "snv_state_plan", "implemented", false, true, {"ssfv:symphony:snv-engine"}, {"propose"}, "qxctl_required", "symphony.snv.state-plan-input.v1", "symphony.snv.state-plan.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:snv.snv-state-reduce", "snv_state_reduce", "implemented", false, true, {"ssfv:symphony:snv-engine"}, {"apply","recover"}, "qxctl_required", "symphony.snv.state-reduce-input.v1", "symphony.snv.state-transition.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
}; }
}
