// Generated by owner_codegen.cpp; do not edit.
#pragma once
#include "symphony/knowledge/engine/operation.hpp"
namespace symphony::snv::sniv::interface {
namespace engine = symphony::knowledge::engine;
inline constexpr auto version = "0.1.0-dev";
inline std::vector<engine::OperationSpec> interface_operations() { return {
  {"engop:symphony:sniv.identity-validate", "identity_validate", "implemented", false, true, {"ssfv:symphony:sniv-engine"}, {"validate","propose"}, "qxctl_required", "symphony.sniv.identity-validate-input.v1", "symphony.sniv.identity-validate.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
}; }
}
