// Generated by tools/shv-interface-codegen/generate.cpp; do not edit.
#pragma once
#include <array>
#include <vector>
#include <string>
namespace symphony::knowledge::shv_source {
inline constexpr auto version = "0.2.0-dev";
struct InterfaceOperation { const char *id; const char *name; const char *input; const char *output; std::vector<std::string> interactions; bool expected_state; };
inline const std::array<InterfaceOperation, 8> interface_operations = {{
  {"engop:symphony:shv-source.inspect", "inspect", "symphony.shv.source-inspect-input.v1", "symphony.knowledge.engine-descriptor.v2", {"inspect"}, false},
  {"engop:symphony:shv-source.source.plan", "source_plan", "symphony.shv.source-plan-input.v1", "symphony.shv.source-plan.v1", {"invoke"}, true},
  {"engop:symphony:shv-source.source.reduce", "source_reduce", "symphony.shv.source-reduce-input.v1", "symphony.shv.source-transition.v1", {"invoke"}, true},
  {"engop:symphony:shv-source.source.status", "source_status", "symphony.shv.source-status-input.v1", "symphony.shv.source-status.v1", {"inspect"}, false},
  {"engop:symphony:shv-source.capture.import", "capture_import", "symphony.shv.capture-import-input.v1", "symphony.shv.source-capture.v1", {"invoke"}, false},
  {"engop:symphony:shv-source.capture.compare", "capture_compare", "symphony.shv.capture-compare-input.v1", "symphony.shv.capture-comparison.v1", {"invoke"}, false},
  {"engop:symphony:shv-source.graph.project", "graph_project", "symphony.shv.source-graph-project-input.v1", "symphony.graph.exchange.v1", {"invoke"}, false},
  {"engop:symphony:shv-source.graph.validate", "graph_validate", "symphony.shv.source-graph-validate-input.v1", "symphony.shv.source-graph-validation.v1", {"invoke"}, false},
}};
}
