// Generated by owner_codegen.cpp; do not edit.
#pragma once
#include "symphony/knowledge/engine/operation.hpp"
namespace symphony::sqmv::administration {
namespace engine = symphony::knowledge::engine;
inline constexpr auto version = "0.1.0-dev";
inline std::vector<engine::OperationSpec> interface_operations() { return {
  {"engop:symphony:sqmv-metadata.validate", "metadata_validate", "implemented", false, true, {"ssfv:symphony:sqmv-metadata-engine"}, {"validate"}, "qxctl_required", "symphony.sqmv.metadata-validate-input.v1", "symphony.sqmv.metadata-validate.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:sqmv-metadata.inspect", "metadata_inspect", "implemented", false, true, {"ssfv:symphony:sqmv-metadata-engine"}, {"inspect"}, "qxctl_required", "symphony.sqmv.metadata-inspect-input.v1", "symphony.sqmv.metadata-inspect.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
}; }
}
