"""Bounded SHV source/publication authoring generator. Never generates semantics."""

from pathlib import Path
import argparse, hashlib, json, re, subprocess

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent


def read(p):
    def pairs(items):
        d = {}
        for k, v in items:
            if k in d:
                raise ValueError("duplicate JSON key: " + k)
            d[k] = v
        return d

    return json.loads(p.read_text(), object_pairs_hook=pairs)


def validate(d, root=ROOT):
    assert set(d) == {
        "protocol",
        "module_id",
        "engine_id",
        "namespace",
        "current_version",
        "releases",
        "contract_versions",
        "operations",
        "schemas",
        "companions",
        "embedded_dependencies",
    }
    lock = read(HERE / "history-lock.json")
    m = d["module_id"]
    assert m in lock
    assert d["protocol"] == "symphony.shv.owner-interface.v1" and all(
        d[k] == lock[m][k] for k in ["namespace", "engine_id", "embedded_dependencies"]
    )
    hp = root / "modules" / m / "tests/fixtures/interface-history.v1.json"
    assert (
        hashlib.sha256(hp.read_bytes()).hexdigest() == lock[m]["history_digest"]
    ), "frozen history changed"
    hist = read(hp)["descriptors"]
    current = d["current_version"]
    assert re.fullmatch(r"0\.[1-9][0-9]*\.0-dev", current) and current not in hist
    assert set(d["releases"]) == set(hist) | {current}
    ops = d["operations"]
    names = [o["operation_name"] for o in ops]
    assert len(names) == len(set(names))
    for version, desc in hist.items():
        assert d["releases"][version] == [
            o["operation_name"] for o in desc["operations"]
        ]
        assert [
            o for o in ops if o["operation_name"] in d["releases"][version]
        ] == desc["operations"], "historical operation change"
    latest = list(hist)[-1]
    assert (
        ops == hist[latest]["operations"]
        and d["releases"][current] == names
        and d["contract_versions"] == hist[latest]["contract_versions"]
    )
    schema_prefix = "modules/" + m + "/schemas/v1/"
    expected = sorted(
        p.relative_to(root).as_posix() for p in (root / schema_prefix).glob("*.json")
    )
    assert d["schemas"] == expected and len(expected) > 0
    assert d["companions"] == [
        "knowledge/shv/"
        + ("SOURCES.md" if m == "shv-source-engine" else "PUBLICATION.md")
    ]
    for path in d["schemas"] + d["companions"]:
        p = Path(path)
        assert not p.is_absolute() and ".." not in p.parts and p.as_posix() == path
        q = root / p
        assert (
            q.is_file()
            and not q.is_symlink()
            and q.resolve().is_relative_to(root.resolve())
        )
    for path in d["schemas"]:
        doc = read(root / path)

        def visit(x):
            if isinstance(x, dict):
                if "$ref" in x:
                    ref = x["$ref"]
                    assert ref.startswith("#/"), "nonlocal schema reference"
                    t = doc
                    for part in ref[2:].split("/"):
                        t = t[part.replace("~1", "/").replace("~0", "~")]
                for v in x.values():
                    visit(v)
            elif isinstance(x, list):
                for v in x:
                    visit(v)

        visit(doc)
    return d


def outputs(d):
    m = d["module_id"]
    short = m.removeprefix("shv-").removesuffix("-engine")
    title = short.title()
    q = lambda x: json.dumps(x, ensure_ascii=True)
    ops = d["operations"]
    digest = (
        "sha256:"
        + hashlib.sha256(
            json.dumps(d, sort_keys=True, separators=(",", ":")).encode()
        ).hexdigest()
    )
    cpp = (
        "// Generated by tools/shv-interface-codegen/generate.py; do not edit.\n#pragma once\n#include <array>\n#include <vector>\n#include <string>\nnamespace "
        + d["namespace"]
        + " {\ninline constexpr auto version = "
        + q(d["current_version"])
        + ";\nstruct InterfaceOperation { const char *id; const char *name; const char *input; const char *output; std::vector<std::string> interactions; bool expected_state; };\ninline const std::array<InterfaceOperation, "
        + str(len(ops))
        + "> interface_operations = {{\n"
    )
    for o in ops:
        cpp += (
            "  {"
            + ", ".join(
                q(o[k])
                for k in [
                    "engine_operation_id",
                    "operation_name",
                    "input_protocol",
                    "output_protocol",
                ]
            )
            + ", "
            + "{"
            + ", ".join(q(i) for i in o["administrative_interactions"])
            + "}"
            + ", "
            + str(o["expected_state_required"]).lower()
            + "},\n"
        )
    cpp += "}};\n}\n"
    go = (
        "// Code generated by tools/shv-interface-codegen/generate.py; DO NOT EDIT.\npackage knowledgeengine\nconst SHV"
        + title
        + "InterfaceVersion = "
        + q(d["current_version"])
        + "\nconst shv"
        + title
        + "InterfaceDigest = "
        + q(digest)
        + "\nvar shv"
        + title
        + "Outputs = map[string]string{\n"
    )
    for o in ops:
        go += q(o["operation_name"]) + ": " + q(o["output_protocol"]) + ",\n"
    go += "}\nvar shv" + title + "Admission = map[string]map[string]bool{\n"
    for v, names in d["releases"].items():
        go += q(v) + ": {" + ", ".join(q(n) + ": true" for n in names) + "},\n"
    go += "}\n"
    go = subprocess.check_output(["gofmt"], input=go.encode()).decode()
    cm = (
        '# Generated by tools/shv-interface-codegen/generate.py; do not edit.\nset(SHV_OWNER_VERSION "'
        + d["current_version"].removesuffix("-dev")
        + '")\n'
    )
    for key, var in [
        ("schemas", "SHV_OWNER_SCHEMA_FILES"),
        ("companions", "SHV_OWNER_COMPANIONS"),
    ]:
        cm += (
            "set("
            + var
            + "\n"
            + "".join(' "${SYMPHONY_REPOSITORY_ROOT}/' + p + '"\n' for p in d[key])
            + ")\n"
        )
    return {
        "modules/" + m + "/src/interface.generated.hpp": cpp,
        "tools/qxctl/internal/knowledgeengine/shv_"
        + short
        + "_interface_generated.go": go,
        "cmake/Shv" + title + "Interface.generated.cmake": cm,
    }


def emit(d, root=ROOT, check=False):
    for path, body in outputs(d).items():
        p = root / path
        if check:
            assert p.read_text() == body, "generated drift: " + path
        else:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(body)


def main():
    p = argparse.ArgumentParser()
    p.add_argument(
        "--owner", required=True, choices=list(read(HERE / "history-lock.json"))
    )
    p.add_argument("--check", action="store_true")
    a = p.parse_args()
    d = validate(read(ROOT / "modules" / a.owner / "OWNER-INTERFACE.json"))
    emit(d, check=a.check)
    print(a.owner, "checked" if a.check else "generated")


if __name__ == "__main__":
    main()
