// Generated by owner_codegen.cpp; do not edit.
#pragma once
#include "symphony/knowledge/engine/operation.hpp"
namespace symphony::sqdv::administration {
namespace engine = symphony::knowledge::engine;
inline constexpr auto version = "0.1.0-dev";
inline std::vector<engine::OperationSpec> interface_operations() { return {
  {"engop:symphony:sqdv-checkpoint.inspect", "checkpoint_inspect", "implemented", false, true, {"ssfv:symphony:sqdv-checkpoint-engine"}, {"inspect"}, "qxctl_required", "symphony.sqdv.checkpoint-inspect-input.v1", "symphony.sqdv.checkpoint-inspect.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
}; }
}
