// Generated by owner_codegen.py; do not edit.
#pragma once
#include "symphony/knowledge/engine/operation.hpp"
namespace symphony::knowledge::shv_partition {
namespace engine = symphony::knowledge::engine;
#ifdef SYMPHONY_SHV_PARTITION_EMBEDDED_PREVIOUS
inline constexpr auto version = "0.2.0-dev";
#else
inline constexpr auto version = "0.3.0-dev";
#endif
inline std::vector<engine::OperationSpec> interface_operations() { return {
  {"engop:symphony:shv-partition.inspect", "inspect", "implemented", false, true, {"ssfv:symphony:shv-partition-engine"}, {"inspect"}, "qxctl_required", "symphony.shv.partition-inspect-input.v1", "symphony.knowledge.engine-descriptor.v2", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:shv-partition.partition.build", "partition_build", "implemented", false, true, {"ssfv:symphony:shv-partition-engine"}, {"invoke"}, "qxctl_required", "symphony.shv.partition-build-input.v1", "symphony.shv.partition.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:shv-partition.manifest.build", "manifest_build", "implemented", false, true, {"ssfv:symphony:shv-partition-engine"}, {"invoke"}, "qxctl_required", "symphony.shv.partition-manifest-build-input.v1", "symphony.shv.partition-manifest.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:shv-partition.manifest.query", "manifest_query", "implemented", false, true, {"ssfv:symphony:shv-partition-engine"}, {"query"}, "qxctl_required", "symphony.shv.partition-manifest-query-input.v1", "symphony.shv.partition-query.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
}; }
}
