// Generated by owner_codegen.cpp; do not edit.
#pragma once
#include "symphony/knowledge/engine/operation.hpp"
namespace symphony::knowledge::shv_pdf {
namespace engine = symphony::knowledge::engine;
#ifdef SYMPHONY_SHV_PDF_EMBEDDED_PREVIOUS
inline constexpr auto version = "0.2.0-dev";
#else
inline constexpr auto version = "0.3.0-dev";
#endif
inline std::vector<engine::OperationSpec> interface_operations() { return {
  {"engop:symphony:shv-pdf.inspect", "inspect", "implemented", false, true, {"ssfv:symphony:shv-pdf-adapter"}, {"inspect"}, "qxctl_required", "symphony.shv.pdf-inspect-input.v1", "symphony.knowledge.engine-descriptor.v2", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:shv-pdf.extract", "extract", "implemented", false, true, {"ssfv:symphony:shv-pdf-adapter"}, {"invoke"}, "qxctl_required", "symphony.shv.pdf-extract-input.v1", "symphony.shv.pdf-extraction.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:shv-pdf.graph.project", "graph_project", "implemented", false, true, {"ssfv:symphony:shv-pdf-adapter"}, {"invoke"}, "qxctl_required", "symphony.shv.pdf-graph-project-input.v1", "symphony.graph.exchange.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:shv-pdf.graph.validate", "graph_validate", "implemented", false, true, {"ssfv:symphony:shv-pdf-adapter"}, {"invoke"}, "qxctl_required", "symphony.shv.pdf-graph-validate-input.v1", "symphony.shv.pdf-graph-validation.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
}; }
}
