// Code generated by owner_codegen.cpp for sbv-engine; DO NOT EDIT.
package knowledgeengine

const SBVAdministrationInterfaceVersion = "0.20.0-dev"
const sbvAdministrationInterfaceDigest = "sha256:b23cb6a18389e342e647bdcd13b87dc4b62f47595c9091719d440902b1c82d4b"

var sbvAdministrationInterfaceOutputs = map[string]string{
	"capabilities":         "symphony.sbv.capabilities.v1",
	"run":                  "symphony.sbv.run.v1",
	"compose":              "symphony.sbv.compose.v1",
	"result_inspect":       "symphony.sbv.result-inspect.v1",
	"result_query":         "symphony.sbv.result-query.v1",
	"evaluate":             "symphony.sbv.evaluate.v1",
	"catalogue":            "symphony.sbv.catalogue.v1",
	"compose_joint":        "symphony.sbv.compose-joint.v1",
	"economics":            "symphony.sbv.economics.v1",
	"book":                 "symphony.sbv.book.v1",
	"liquidity":            "symphony.sbv.liquidity.v1",
	"allocation_economics": "symphony.sbv.allocation-economics.v1",
	"result_select":        "symphony.sbv.result-select.v1",
	"backend_plan":         "symphony.sbv.backend-plan.v1",
	"live_plan":            "symphony.sbv.live-plan.v1",
	"analyze":              "symphony.sbv.analyze.v1",
	"compare":              "symphony.sbv.compare.v1",
	"resample":             "symphony.sbv.resample.v1",
	"experiment":           "symphony.sbv.experiment.v1",
	"split":                "symphony.sbv.split.v1",
	"dataset_load":         "symphony.sbv.dataset-load.v1",
	"dataset_inspect":      "symphony.sbv.dataset-inspect.v1",
	"dataset_execute":      "symphony.sbv.dataset-execute.v1",
	"dataset_release":      "symphony.sbv.dataset-release.v1",
	"fit":                  "symphony.sbv.fit.v1",
	"predict":              "symphony.sbv.predict.v1",
	"research_history":     "symphony.sbv.research-history.v1",
	"compose_economics":    "symphony.sbv.compose-economics.v1",
	"generate_census":      "symphony.sbv.generate-census.v1",
	"provider_inspect":     "symphony.sbv.provider-inspect.v1",
}
var sbvAdministrationInterfaceAdmission = map[string]map[string]bool{
	"0.20.0-dev": {"capabilities": true, "run": true, "compose": true, "result_inspect": true, "result_query": true, "evaluate": true, "catalogue": true, "compose_joint": true, "economics": true, "book": true, "liquidity": true, "allocation_economics": true, "result_select": true, "backend_plan": true, "live_plan": true, "analyze": true, "compare": true, "resample": true, "experiment": true, "split": true, "dataset_load": true, "dataset_inspect": true, "dataset_execute": true, "dataset_release": true, "fit": true, "predict": true, "research_history": true, "compose_economics": true, "generate_census": true, "provider_inspect": true},
}

var sbvAdministrationInterfaceResources = map[string]string{
	"admin.schema.json":          "sha256:094e02a01cbcd84fa1ec24e7122baad75a56e3c187eb2c0370329a81da7f3a1b",
	"admin.templates.json":       "sha256:ffe683f8e15b38ae999daa92051beaf5c24d477403b955566e1d8c8faa981f6b",
	"result.schema.json":         "sha256:94d6c9e021db44b7e36951d0a8a06dea00b35c522a0c93c6a2d81eb59cfa60af",
	"pointer-stream.schema.json": "sha256:5f904fc5723b6c0918517509081f8fff436f008496ce6c19c24ac548992a04f3",
}
