// Code generated by owner_codegen.cpp for sbv-engine; DO NOT EDIT.
package knowledgeengine

const SBVAdministrationInterfaceVersion = "0.7.0-dev"
const sbvAdministrationInterfaceDigest = "sha256:dd63889e35691f2bcacc8745cddd1bdb2df03cb9db0ee2614c4a66b7b3cd9a8e"

var sbvAdministrationInterfaceOutputs = map[string]string{
	"capabilities":         "symphony.sbv.capabilities.v1",
	"run":                  "symphony.sbv.run.v1",
	"compose":              "symphony.sbv.compose.v1",
	"result_inspect":       "symphony.sbv.result-inspect.v1",
	"result_query":         "symphony.sbv.result-query.v1",
	"evaluate":             "symphony.sbv.evaluate.v1",
	"catalogue":            "symphony.sbv.catalogue.v1",
	"compose_joint":        "symphony.sbv.compose-joint.v1",
	"economics":            "symphony.sbv.economics.v1",
	"book":                 "symphony.sbv.book.v1",
	"liquidity":            "symphony.sbv.liquidity.v1",
	"allocation_economics": "symphony.sbv.allocation-economics.v1",
	"result_select":        "symphony.sbv.result-select.v1",
	"backend_plan":         "symphony.sbv.backend-plan.v1",
	"live_plan":            "symphony.sbv.live-plan.v1",
}
var sbvAdministrationInterfaceAdmission = map[string]map[string]bool{
	"0.7.0-dev": {"capabilities": true, "run": true, "compose": true, "result_inspect": true, "result_query": true, "evaluate": true, "catalogue": true, "compose_joint": true, "economics": true, "book": true, "liquidity": true, "allocation_economics": true, "result_select": true, "backend_plan": true, "live_plan": true},
}

var sbvAdministrationInterfaceResources = map[string]string{
	"admin.schema.json":          "sha256:2694d12027906ececacbc485bb4bf7ed2c56080fec8ebe1a3de092778ec45293",
	"admin.templates.json":       "sha256:ea220144aa805efb6d5be8efe37e83a38a5ce9720c0f6ed1b32c53146986d2a3",
	"result.schema.json":         "sha256:94d6c9e021db44b7e36951d0a8a06dea00b35c522a0c93c6a2d81eb59cfa60af",
	"pointer-stream.schema.json": "sha256:5f904fc5723b6c0918517509081f8fff436f008496ce6c19c24ac548992a04f3",
}
