// Code generated by owner_codegen.cpp for sciv-engine; DO NOT EDIT.
package knowledgeengine

const SCIVAdministrationInterfaceVersion = "0.1.0-dev"
const scivAdministrationInterfaceDigest = "sha256:3439e7685c3ac6bc2a4059a33a616eb9c0c9863f189fcd40c1e6caabf8cc9d6d"

var scivAdministrationInterfaceOutputs = map[string]string{
	"sciv_validate":   "symphony.snv.sciv.result.v1",
	"sciv_transition": "symphony.snv.sciv.transition-result.v1",
}
var scivAdministrationInterfaceAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"sciv_validate": true, "sciv_transition": true},
}

var scivAdministrationInterfaceResources = map[string]string{
	"sciv-evidence.schema.json":          "sha256:9ed88b417e05ed2ff6ebe320def1a8d2cc20684349641380d80881c841ee203b",
	"sciv-evidence.template.json":        "sha256:4cc6db3f9bb0b3b1273dd566fcea87899f0379baea4d76b89c77b3111a5bbe0a",
	"sciv-result.schema.json":            "sha256:8257fc5c2034c19c65f1cc3e98335655326afb69118150b48eaa6b78c2a44ec8",
	"sciv-transition-result.schema.json": "sha256:b4272bd85b83e39f7912eb033cc02cdb1beed1eb6414154facf21f742fcd88a4",
	"sciv-transition.schema.json":        "sha256:a7dff89d7b1c5556cf0e97b846422f7339379c837dda4e657175460c906c3f55",
	"sciv-transition.template.json":      "sha256:cc3fc393eb7b9cf4bc31e4cae224fad790b4f52193b6a1cb67adfa6be5d7b469",
}
