// Code generated by owner_codegen.cpp for scnv-engine; DO NOT EDIT.
package knowledgeengine

const SCNVAdministrationInterfaceVersion = "0.1.0-dev"
const scnvAdministrationInterfaceDigest = "sha256:752ce39d71e03cd991710bebebfb63597e2d4ab805afc05b8725028e187c699b"

var scnvAdministrationInterfaceOutputs = map[string]string{
	"names_validate": "scnv.names-result.v1",
	"names_resolve":  "scnv.resolve-result.v1",
}
var scnvAdministrationInterfaceAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"names_validate": true, "names_resolve": true},
}

var scnvAdministrationInterfaceResources = map[string]string{
	"admin.templates.json":       "sha256:280f8a19011ac947ffbb0ab1c1151651d503df240ce4f7ffbe67d34eecdba6a9",
	"names-result.schema.json":   "sha256:f9cdfebf64bccc0e3eb8a1ec8526a60cf30b793bfcce950eb7223a78dc2a8441",
	"names.schema.json":          "sha256:1faf99ff3173ad49a910a4806763dbaa2b5287d68eab8e32d201634024bad6d8",
	"resolve-result.schema.json": "sha256:b43eedfa06755fef148c2a6f5b0421a9c37448a2c720ee2fd06634d823342a9a",
	"resolve.schema.json":        "sha256:e9d1df456fb6c01af8a9350ed7b7a9141cc727d2c2a0ceb214ec95d3a3f92278",
}
