// Code generated by modules/scv-engine/tools/generate_interface.py; DO NOT EDIT.
// Owner interface SHA-256: sha256:f83d5d40ed3b34717736725a1816426fae8021cf32aaf126d6164c2a6a972330
package knowledgeengine

type SCVOperationInterface struct {
	InputProtocol  string
	OutputProtocol string
	Interactions   []string
	Mutability     string
	ExpectedState  bool
}
type scvReleaseInterface struct {
	operations map[string]bool
	artifacts  map[string]bool
	surfaces   map[string]bool
	domains    map[string]bool
	companions []string
}

var scvInterfaceDomains = []string{"scv", "schv", "scev", "schv-aws", "schv-azure", "schv-do", "schv-gcp", "scev-cf"}
var scvInterfaceOperations = map[string]SCVOperationInterface{
	"inspect":                     {InputProtocol: "symphony.scv.inspect-input.v1", OutputProtocol: "symphony.knowledge.engine-descriptor.v2", Interactions: []string{"inspect"}, Mutability: "read_only", ExpectedState: false},
	"provider_onboard":            {InputProtocol: "symphony.scv.provider-onboard-input.v1", OutputProtocol: "symphony.scv.provider.v1", Interactions: []string{"discover"}, Mutability: "proposal_only", ExpectedState: false},
	"source_plan":                 {InputProtocol: "symphony.scv.source-plan-input.v1", OutputProtocol: "symphony.scv.source-plan.v1", Interactions: []string{"propose"}, Mutability: "proposal_only", ExpectedState: true},
	"source_apply":                {InputProtocol: "symphony.scv.source-apply-input.v1", OutputProtocol: "symphony.scv.source-transition.v1", Interactions: []string{"apply", "recover"}, Mutability: "proposal_only", ExpectedState: true},
	"source_status":               {InputProtocol: "symphony.scv.source-status-input.v1", OutputProtocol: "symphony.scv.source-status.v1", Interactions: []string{"inspect"}, Mutability: "read_only", ExpectedState: false},
	"capture_import":              {InputProtocol: "symphony.scv.capture-import-input.v1", OutputProtocol: "symphony.scv.capture.v1", Interactions: []string{"invoke"}, Mutability: "evidence_only", ExpectedState: false},
	"capture_compare":             {InputProtocol: "symphony.scv.capture-compare-input.v1", OutputProtocol: "symphony.scv.capture-diff.v1", Interactions: []string{"validate"}, Mutability: "evidence_only", ExpectedState: false},
	"knowledge_interpret":         {InputProtocol: "symphony.scv.knowledge-interpret-input.v1", OutputProtocol: "symphony.scv.knowledge.v1", Interactions: []string{"invoke"}, Mutability: "evidence_only", ExpectedState: false},
	"graph_build":                 {InputProtocol: "symphony.scv.graph-build-input.v1", OutputProtocol: "symphony.scv.graph.v1", Interactions: []string{"invoke"}, Mutability: "evidence_only", ExpectedState: false},
	"graph_query":                 {InputProtocol: "symphony.scv.graph-query-input.v1", OutputProtocol: "symphony.scv.query-result.v1", Interactions: []string{"query"}, Mutability: "read_only", ExpectedState: false},
	"graph_diff":                  {InputProtocol: "symphony.scv.graph-diff-input.v1", OutputProtocol: "symphony.scv.diff-result.v1", Interactions: []string{"validate"}, Mutability: "evidence_only", ExpectedState: false},
	"graph_explain":               {InputProtocol: "symphony.scv.graph-explain-input.v1", OutputProtocol: "symphony.scv.explain-result.v1", Interactions: []string{"query"}, Mutability: "read_only", ExpectedState: false},
	"graph_evaluate":              {InputProtocol: "symphony.scv.graph-evaluate-input.v1", OutputProtocol: "symphony.scv.evaluate-result.v1", Interactions: []string{"validate"}, Mutability: "evidence_only", ExpectedState: false},
	"capture_index":               {InputProtocol: "symphony.scv.capture-index-input.v1", OutputProtocol: "symphony.scv.capture-index.v1", Interactions: []string{"invoke"}, Mutability: "evidence_only", ExpectedState: false},
	"corpus_build":                {InputProtocol: "symphony.scv.corpus-build-input.v1", OutputProtocol: "symphony.scv.corpus.v1", Interactions: []string{"invoke"}, Mutability: "evidence_only", ExpectedState: false},
	"corpus_query":                {InputProtocol: "symphony.scv.corpus-query-input.v1", OutputProtocol: "symphony.scv.corpus-query.v1", Interactions: []string{"query"}, Mutability: "read_only", ExpectedState: false},
	"corpus_diff":                 {InputProtocol: "symphony.scv.corpus-diff-input.v1", OutputProtocol: "symphony.scv.corpus-diff.v1", Interactions: []string{"validate"}, Mutability: "evidence_only", ExpectedState: false},
	"provider_interpret":          {InputProtocol: "symphony.scv.provider-interpret-input.v1", OutputProtocol: "symphony.scv.provider-interpretation.v1", Interactions: []string{"invoke"}, Mutability: "evidence_only", ExpectedState: false},
	"connection_evaluate":         {InputProtocol: "symphony.scv.connection-evaluate-input.v1", OutputProtocol: "symphony.scv.connection-evaluation.v1", Interactions: []string{"validate"}, Mutability: "evidence_only", ExpectedState: false},
	"connection_reassess":         {InputProtocol: "symphony.scv.connection-reassess-input.v1", OutputProtocol: "symphony.scv.connection-reassessment.v1", Interactions: []string{"validate"}, Mutability: "evidence_only", ExpectedState: false},
	"profile_prepare":             {InputProtocol: "symphony.scv.profile-prepare-input.v1", OutputProtocol: "symphony.scv.interpretation-profile.v1", Interactions: []string{"propose"}, Mutability: "proposal_only", ExpectedState: false},
	"provider_coverage":           {InputProtocol: "symphony.scv.provider-coverage-input.v1", OutputProtocol: "symphony.scv.provider-coverage.v1", Interactions: []string{"query"}, Mutability: "read_only", ExpectedState: false},
	"provider_pack_prepare":       {InputProtocol: "symphony.scv.provider-pack-prepare-input.v1", OutputProtocol: "symphony.scv.provider-pack.v1", Interactions: []string{"propose"}, Mutability: "proposal_only", ExpectedState: false},
	"provider_pack_evaluate":      {InputProtocol: "symphony.scv.provider-pack-evaluate-input.v1", OutputProtocol: "symphony.scv.provider-pack-evaluation.v1", Interactions: []string{"query"}, Mutability: "read_only", ExpectedState: false},
	"composition_explore":         {InputProtocol: "symphony.scv.composition-explore-input.v1", OutputProtocol: "symphony.scv.composition-exploration.v1", Interactions: []string{"query"}, Mutability: "read_only", ExpectedState: false},
	"composition_reassess":        {InputProtocol: "symphony.scv.composition-reassess-input.v1", OutputProtocol: "symphony.scv.composition-reassessment.v1", Interactions: []string{"validate"}, Mutability: "evidence_only", ExpectedState: false},
	"composition_obligations":     {InputProtocol: "symphony.scv.composition-obligations-input.v1", OutputProtocol: "symphony.scv.composition-obligations.v1", Interactions: []string{"query"}, Mutability: "read_only", ExpectedState: false},
	"composition_followup":        {InputProtocol: "symphony.scv.composition-followup-input.v1", OutputProtocol: "symphony.scv.composition-followup.v1", Interactions: []string{"validate"}, Mutability: "evidence_only", ExpectedState: false},
	"bundle_inspect":              {InputProtocol: "symphony.scv.bundle-inspect-input.v1", OutputProtocol: "symphony.scv.bundle-inspection.v1", Interactions: []string{"inspect"}, Mutability: "read_only", ExpectedState: false},
	"composition_bundle_evaluate": {InputProtocol: "symphony.scv.composition-bundle-evaluate-input.v1", OutputProtocol: "symphony.scv.composition-bundle-evaluation.v1", Interactions: []string{"validate"}, Mutability: "evidence_only", ExpectedState: false},
}
var scvInterfaceArtifacts = map[string]struct{ kind, minimumRelease string }{
	"provider_onboard":            {"provider", "0.5.0-dev"},
	"knowledge_interpret":         {"knowledge", "0.3.0-dev"},
	"provider_interpret":          {"interpretation", "0.3.0-dev"},
	"connection_evaluate":         {"evaluation", "0.3.0-dev"},
	"connection_reassess":         {"reassessment", "0.3.0-dev"},
	"profile_prepare":             {"profile", "0.4.0-dev"},
	"provider_coverage":           {"coverage", "0.5.0-dev"},
	"provider_pack_prepare":       {"provider_pack", "0.6.0-dev"},
	"provider_pack_evaluate":      {"provider_pack_evaluation", "0.6.0-dev"},
	"composition_explore":         {"composition", "0.6.0-dev"},
	"composition_reassess":        {"composition_reassessment", "0.6.0-dev"},
	"composition_obligations":     {"composition_obligations", "0.8.0-dev"},
	"composition_followup":        {"composition_followup", "0.8.0-dev"},
	"bundle_inspect":              {"bundle_inspection", "0.9.0-dev"},
	"composition_bundle_evaluate": {"composition_bundle_evaluation", "0.9.0-dev"},
}
var scvInterfaceReleases = map[string]scvReleaseInterface{
	"0.1.0-dev": {operations: map[string]bool{"inspect": true, "provider_onboard": true, "source_plan": true, "source_apply": true, "source_status": true, "capture_import": true, "capture_compare": true, "knowledge_interpret": true, "graph_build": true, "graph_query": true, "graph_diff": true, "graph_explain": true, "graph_evaluate": true}, artifacts: map[string]bool{}, surfaces: map[string]bool{}, domains: map[string]bool{"scv": true, "schv": true, "scev": true, "schv-aws": true, "schv-azure": true, "schv-do": true, "schv-gcp": true, "scev-cf": true}, companions: []string{"SOURCE-KNOWLEDGE.md"}},
	"0.2.0-dev": {operations: map[string]bool{"inspect": true, "provider_onboard": true, "source_plan": true, "source_apply": true, "source_status": true, "capture_import": true, "capture_compare": true, "knowledge_interpret": true, "graph_build": true, "graph_query": true, "graph_diff": true, "graph_explain": true, "graph_evaluate": true, "capture_index": true, "corpus_build": true, "corpus_query": true, "corpus_diff": true}, artifacts: map[string]bool{}, surfaces: map[string]bool{"corpus": true}, domains: map[string]bool{"scv": true, "schv": true, "scev": true, "schv-aws": true, "schv-azure": true, "schv-do": true, "schv-gcp": true, "scev-cf": true}, companions: []string{"SOURCE-KNOWLEDGE.md", "CORPUS.md"}},
	"0.3.0-dev": {operations: map[string]bool{"inspect": true, "provider_onboard": true, "source_plan": true, "source_apply": true, "source_status": true, "capture_import": true, "capture_compare": true, "knowledge_interpret": true, "graph_build": true, "graph_query": true, "graph_diff": true, "graph_explain": true, "graph_evaluate": true, "capture_index": true, "corpus_build": true, "corpus_query": true, "corpus_diff": true, "provider_interpret": true, "connection_evaluate": true, "connection_reassess": true}, artifacts: map[string]bool{"knowledge_interpret": true, "provider_interpret": true, "connection_evaluate": true, "connection_reassess": true}, surfaces: map[string]bool{"corpus": true, "workflow": true, "artifact": true}, domains: map[string]bool{"scv": true, "schv": true, "scev": true, "schv-aws": true, "schv-azure": true, "schv-do": true, "schv-gcp": true, "scev-cf": true}, companions: []string{"SOURCE-KNOWLEDGE.md", "CORPUS.md", "INTERPRETATION.md"}},
	"0.4.0-dev": {operations: map[string]bool{"inspect": true, "provider_onboard": true, "source_plan": true, "source_apply": true, "source_status": true, "capture_import": true, "capture_compare": true, "knowledge_interpret": true, "graph_build": true, "graph_query": true, "graph_diff": true, "graph_explain": true, "graph_evaluate": true, "capture_index": true, "corpus_build": true, "corpus_query": true, "corpus_diff": true, "provider_interpret": true, "connection_evaluate": true, "connection_reassess": true, "profile_prepare": true}, artifacts: map[string]bool{"knowledge_interpret": true, "provider_interpret": true, "connection_evaluate": true, "connection_reassess": true, "profile_prepare": true}, surfaces: map[string]bool{"corpus": true, "workflow": true, "artifact": true, "schema": true}, domains: map[string]bool{"scv": true, "schv": true, "scev": true, "schv-aws": true, "schv-azure": true, "schv-do": true, "schv-gcp": true, "scev-cf": true}, companions: []string{"SOURCE-KNOWLEDGE.md", "CORPUS.md", "INTERPRETATION.md", "AGENT-WORKFLOWS.md"}},
	"0.5.0-dev": {operations: map[string]bool{"inspect": true, "provider_onboard": true, "source_plan": true, "source_apply": true, "source_status": true, "capture_import": true, "capture_compare": true, "knowledge_interpret": true, "graph_build": true, "graph_query": true, "graph_diff": true, "graph_explain": true, "graph_evaluate": true, "capture_index": true, "corpus_build": true, "corpus_query": true, "corpus_diff": true, "provider_interpret": true, "connection_evaluate": true, "connection_reassess": true, "profile_prepare": true, "provider_coverage": true}, artifacts: map[string]bool{"provider_onboard": true, "knowledge_interpret": true, "provider_interpret": true, "connection_evaluate": true, "connection_reassess": true, "profile_prepare": true, "provider_coverage": true}, surfaces: map[string]bool{"corpus": true, "workflow": true, "artifact": true, "schema": true}, domains: map[string]bool{"scv": true, "schv": true, "scev": true, "schv-aws": true, "schv-azure": true, "schv-do": true, "schv-gcp": true, "scev-cf": true}, companions: []string{"SOURCE-KNOWLEDGE.md", "CORPUS.md", "INTERPRETATION.md", "AGENT-WORKFLOWS.md", "COVERAGE.md"}},
	"0.6.0-dev": {operations: map[string]bool{"inspect": true, "provider_onboard": true, "source_plan": true, "source_apply": true, "source_status": true, "capture_import": true, "capture_compare": true, "knowledge_interpret": true, "graph_build": true, "graph_query": true, "graph_diff": true, "graph_explain": true, "graph_evaluate": true, "capture_index": true, "corpus_build": true, "corpus_query": true, "corpus_diff": true, "provider_interpret": true, "connection_evaluate": true, "connection_reassess": true, "profile_prepare": true, "provider_coverage": true, "provider_pack_prepare": true, "provider_pack_evaluate": true, "composition_explore": true, "composition_reassess": true}, artifacts: map[string]bool{"provider_onboard": true, "knowledge_interpret": true, "provider_interpret": true, "connection_evaluate": true, "connection_reassess": true, "profile_prepare": true, "provider_coverage": true, "provider_pack_prepare": true, "provider_pack_evaluate": true, "composition_explore": true, "composition_reassess": true}, surfaces: map[string]bool{"corpus": true, "workflow": true, "artifact": true, "schema": true, "interface": true}, domains: map[string]bool{"scv": true, "schv": true, "scev": true, "schv-aws": true, "schv-azure": true, "schv-do": true, "schv-gcp": true, "scev-cf": true}, companions: []string{"SOURCE-KNOWLEDGE.md", "CORPUS.md", "INTERPRETATION.md", "AGENT-WORKFLOWS.md", "COVERAGE.md", "PROVIDER-PACKS.md", "COMPOSITION.md", "OWNER-INTERFACE.md"}},
	"0.7.0-dev": {operations: map[string]bool{"inspect": true, "provider_onboard": true, "source_plan": true, "source_apply": true, "source_status": true, "capture_import": true, "capture_compare": true, "knowledge_interpret": true, "graph_build": true, "graph_query": true, "graph_diff": true, "graph_explain": true, "graph_evaluate": true, "capture_index": true, "corpus_build": true, "corpus_query": true, "corpus_diff": true, "provider_interpret": true, "connection_evaluate": true, "connection_reassess": true, "profile_prepare": true, "provider_coverage": true, "provider_pack_prepare": true, "provider_pack_evaluate": true, "composition_explore": true, "composition_reassess": true}, artifacts: map[string]bool{"provider_onboard": true, "knowledge_interpret": true, "provider_interpret": true, "connection_evaluate": true, "connection_reassess": true, "profile_prepare": true, "provider_coverage": true, "provider_pack_prepare": true, "provider_pack_evaluate": true, "composition_explore": true, "composition_reassess": true}, surfaces: map[string]bool{"corpus": true, "workflow": true, "artifact": true, "schema": true, "interface": true, "composition_workflow": true}, domains: map[string]bool{"scv": true, "schv": true, "scev": true, "schv-aws": true, "schv-azure": true, "schv-do": true, "schv-gcp": true, "scev-cf": true}, companions: []string{"SOURCE-KNOWLEDGE.md", "CORPUS.md", "INTERPRETATION.md", "AGENT-WORKFLOWS.md", "COVERAGE.md", "PROVIDER-PACKS.md", "COMPOSITION.md", "OWNER-INTERFACE.md", "COMPOSITION-WORKFLOWS.md"}},
	"0.8.0-dev": {operations: map[string]bool{"inspect": true, "provider_onboard": true, "source_plan": true, "source_apply": true, "source_status": true, "capture_import": true, "capture_compare": true, "knowledge_interpret": true, "graph_build": true, "graph_query": true, "graph_diff": true, "graph_explain": true, "graph_evaluate": true, "capture_index": true, "corpus_build": true, "corpus_query": true, "corpus_diff": true, "provider_interpret": true, "connection_evaluate": true, "connection_reassess": true, "profile_prepare": true, "provider_coverage": true, "provider_pack_prepare": true, "provider_pack_evaluate": true, "composition_explore": true, "composition_reassess": true, "composition_obligations": true, "composition_followup": true}, artifacts: map[string]bool{"provider_onboard": true, "knowledge_interpret": true, "provider_interpret": true, "connection_evaluate": true, "connection_reassess": true, "profile_prepare": true, "provider_coverage": true, "provider_pack_prepare": true, "provider_pack_evaluate": true, "composition_explore": true, "composition_reassess": true, "composition_obligations": true, "composition_followup": true}, surfaces: map[string]bool{"corpus": true, "workflow": true, "artifact": true, "schema": true, "interface": true, "composition_workflow": true}, domains: map[string]bool{"scv": true, "schv": true, "scev": true, "schv-aws": true, "schv-azure": true, "schv-do": true, "schv-gcp": true, "scev-cf": true}, companions: []string{"SOURCE-KNOWLEDGE.md", "CORPUS.md", "INTERPRETATION.md", "AGENT-WORKFLOWS.md", "COVERAGE.md", "PROVIDER-PACKS.md", "COMPOSITION.md", "OWNER-INTERFACE.md", "COMPOSITION-WORKFLOWS.md", "OBLIGATIONS.md"}},
	"0.9.0-dev": {operations: map[string]bool{"inspect": true, "provider_onboard": true, "source_plan": true, "source_apply": true, "source_status": true, "capture_import": true, "capture_compare": true, "knowledge_interpret": true, "graph_build": true, "graph_query": true, "graph_diff": true, "graph_explain": true, "graph_evaluate": true, "capture_index": true, "corpus_build": true, "corpus_query": true, "corpus_diff": true, "provider_interpret": true, "connection_evaluate": true, "connection_reassess": true, "profile_prepare": true, "provider_coverage": true, "provider_pack_prepare": true, "provider_pack_evaluate": true, "composition_explore": true, "composition_reassess": true, "composition_obligations": true, "composition_followup": true, "bundle_inspect": true, "composition_bundle_evaluate": true}, artifacts: map[string]bool{"provider_onboard": true, "knowledge_interpret": true, "provider_interpret": true, "connection_evaluate": true, "connection_reassess": true, "profile_prepare": true, "provider_coverage": true, "provider_pack_prepare": true, "provider_pack_evaluate": true, "composition_explore": true, "composition_reassess": true, "composition_obligations": true, "composition_followup": true, "bundle_inspect": true, "composition_bundle_evaluate": true}, surfaces: map[string]bool{"corpus": true, "workflow": true, "artifact": true, "schema": true, "interface": true, "composition_workflow": true}, domains: map[string]bool{"scv": true, "schv": true, "scev": true, "schv-aws": true, "schv-azure": true, "schv-do": true, "schv-gcp": true, "scev-cf": true}, companions: []string{"SOURCE-KNOWLEDGE.md", "CORPUS.md", "INTERPRETATION.md", "AGENT-WORKFLOWS.md", "COVERAGE.md", "PROVIDER-PACKS.md", "COMPOSITION.md", "OWNER-INTERFACE.md", "COMPOSITION-WORKFLOWS.md", "OBLIGATIONS.md", "BUNDLES.md"}},
}

// Interface admission is exact and generated; validation behavior remains independent.
func SCVDomains() []string { return append([]string(nil), scvInterfaceDomains...) }
func SCVOperationMetadata(operation string) (SCVOperationInterface, bool) {
	value, ok := scvInterfaceOperations[operation]
	value.Interactions = append([]string(nil), value.Interactions...)
	return value, ok
}
func SCVResultProtocol(operation string) (string, bool) {
	value, ok := scvInterfaceOperations[operation]
	return value.OutputProtocol, ok
}
func SCVOperationSupported(version, operation string) bool {
	return scvInterfaceReleases[version].operations[operation]
}
func SCVSupports(version, surface string) bool {
	return scvInterfaceReleases[version].surfaces[surface]
}
func SCVDomainSupported(version, domain string) bool {
	return scvInterfaceReleases[version].domains[domain]
}
func SCVArtifactKind(operation string) string { return scvInterfaceArtifacts[operation].kind }
func SCVArtifactMinimumRelease(operation string) string {
	return scvInterfaceArtifacts[operation].minimumRelease
}
func SCVArtifactSupported(version, operation string) bool {
	return scvInterfaceReleases[version].artifacts[operation]
}
func SCVOperationInteraction(operation string) string {
	value := scvInterfaceOperations[operation]
	if len(value.Interactions) == 0 {
		return ""
	}
	return value.Interactions[0]
}
func scvInterfaceOperationCount(version string) int {
	return len(scvInterfaceReleases[version].operations)
}
func scvInterfaceCompanions(version string) []string {
	return append([]string(nil), scvInterfaceReleases[version].companions...)
}

func SCVArtifactOperations() []string {
	return []string{"provider_onboard", "knowledge_interpret", "provider_interpret", "connection_evaluate", "connection_reassess", "profile_prepare", "provider_coverage", "provider_pack_prepare", "provider_pack_evaluate", "composition_explore", "composition_reassess", "composition_obligations", "composition_followup", "bundle_inspect", "composition_bundle_evaluate"}
}

var scvInterfaceDefinitionDigests = map[string]string{
	"0.6.0-dev": "sha256:ad52be4f0992d0441a4d2190059a004e393a2fd0ed2ac31d11410d48918d4f28",
	"0.7.0-dev": "sha256:b41ddc8d6460595a55a2088014886443bc367f89c302d46b1e08e4d980e680ae",
	"0.8.0-dev": "sha256:6f39734290953544f63a6998f78fb70ffba1eebd13e17b7e92e824414323e9e2",
	"0.9.0-dev": "sha256:f83d5d40ed3b34717736725a1816426fae8021cf32aaf126d6164c2a6a972330",
}
