// Code generated by owner_codegen.py for shv-engine; DO NOT EDIT.
package knowledgeengine

const SHVKernelInterfaceVersion = "0.4.0-dev"
const shvKernelInterfaceDigest = "sha256:c8f1cb8e4c6af7a5afb589ca87f02f4bc33fc62f1cc00bcd18a115d0135c3f75"

var shvKernelInterfaceOutputs = map[string]string{
	"inspect":          "symphony.knowledge.engine-descriptor.v2",
	"coverage_default": "symphony.shv.coverage-profile.v1",
	"coverage_plan":    "symphony.shv.coverage-result.v1",
	"catalogue_build":  "symphony.shv.catalogue.v1",
	"catalogue_query":  "symphony.shv.query-result.v1",
	"evaluate":         "symphony.shv.evaluation.v1",
	"graph_project":    "symphony.graph.exchange.v1",
	"graph_validate":   "symphony.shv.graph-validation.v1",
}
var shvKernelInterfaceAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"inspect": true, "coverage_default": true, "coverage_plan": true, "catalogue_build": true, "catalogue_query": true, "evaluate": true, "graph_project": true, "graph_validate": true},
	"0.2.0-dev": {"inspect": true, "coverage_default": true, "coverage_plan": true, "catalogue_build": true, "catalogue_query": true, "evaluate": true, "graph_project": true, "graph_validate": true},
	"0.3.0-dev": {"inspect": true, "coverage_default": true, "coverage_plan": true, "catalogue_build": true, "catalogue_query": true, "evaluate": true, "graph_project": true, "graph_validate": true},
	"0.4.0-dev": {"inspect": true, "coverage_default": true, "coverage_plan": true, "catalogue_build": true, "catalogue_query": true, "evaluate": true, "graph_project": true, "graph_validate": true},
}
