// Code generated by owner_codegen.py for shv-graph-duckdb-connector; DO NOT EDIT.
package knowledgeengine

const SHVStoreInterfaceVersion = "0.4.0-dev"
const shvStoreInterfaceDigest = "sha256:9c5eb741e158c885c0f587a51e17a00c1b5c33e76100ddc64d835d7b2fee060a"

var shvStoreInterfaceOutputs = map[string]string{
	"inspect":       "symphony.knowledge.engine-descriptor.v2",
	"prepare":       "symphony.shv.graph-store-status.v1",
	"commit":        "symphony.shv.graph-store-status.v1",
	"status":        "symphony.shv.graph-store-status.v1",
	"query":         "symphony.shv.graph-store-query.v1",
	"export":        "symphony.shv.graph-store-export.v1",
	"inventory":     "symphony.shv.graph-store-inventory.v1",
	"transfer_plan": "symphony.shv.graph-store-transfer-plan.v1",
}
var shvStoreInterfaceAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"inspect": true, "prepare": true, "commit": true, "status": true, "query": true, "export": true},
	"0.2.0-dev": {"inspect": true, "prepare": true, "commit": true, "status": true, "query": true, "export": true, "inventory": true},
	"0.3.0-dev": {"inspect": true, "prepare": true, "commit": true, "status": true, "query": true, "export": true, "inventory": true, "transfer_plan": true},
	"0.4.0-dev": {"inspect": true, "prepare": true, "commit": true, "status": true, "query": true, "export": true, "inventory": true, "transfer_plan": true},
}
