// Code generated by owner_codegen.py for shv-partition-engine; DO NOT EDIT.
package knowledgeengine

const SHVPartitionInterfaceVersion = "0.4.0-dev"
const shvPartitionInterfaceDigest = "sha256:3fa4da71d9374c1a7c9345b0616f2a353a4395e0ba72bcc298c6942430e353af"

var shvPartitionInterfaceOutputs = map[string]string{
	"inspect":         "symphony.knowledge.engine-descriptor.v2",
	"partition_build": "symphony.shv.partition.v1",
	"manifest_build":  "symphony.shv.partition-manifest.v1",
	"manifest_query":  "symphony.shv.partition-query.v1",
}
var shvPartitionInterfaceAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"inspect": true, "partition_build": true, "manifest_build": true, "manifest_query": true},
	"0.2.0-dev": {"inspect": true, "partition_build": true, "manifest_build": true, "manifest_query": true},
	"0.3.0-dev": {"inspect": true, "partition_build": true, "manifest_build": true, "manifest_query": true},
	"0.4.0-dev": {"inspect": true, "partition_build": true, "manifest_build": true, "manifest_query": true},
}
