// Code generated by owner_codegen.py for shv-partition-engine; DO NOT EDIT.
package knowledgeengine

const SHVPartitionInterfaceVersion = "0.3.0-dev"
const shvPartitionInterfaceDigest = "sha256:d041adaa0b508b668f8b199f93072b49f440358b368f2b6a672bb27fc6df83b4"

var shvPartitionInterfaceOutputs = map[string]string{
	"inspect":         "symphony.knowledge.engine-descriptor.v2",
	"partition_build": "symphony.shv.partition.v1",
	"manifest_build":  "symphony.shv.partition-manifest.v1",
	"manifest_query":  "symphony.shv.partition-query.v1",
}
var shvPartitionInterfaceAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"inspect": true, "partition_build": true, "manifest_build": true, "manifest_query": true},
	"0.2.0-dev": {"inspect": true, "partition_build": true, "manifest_build": true, "manifest_query": true},
	"0.3.0-dev": {"inspect": true, "partition_build": true, "manifest_build": true, "manifest_query": true},
}
