// Code generated by owner_codegen.cpp for shv-graph-adapter; DO NOT EDIT.
package knowledgeengine

const SHVGraphAdapterInterfaceVersion = "0.2.0-dev"
const shvGraphAdapterInterfaceDigest = "sha256:c293aff30cb62bfb1fd1adf1cbbbe8927a4a54de462da0fd9c2c083b76ed317a"

var shvGraphAdapterInterfaceOutputs = map[string]string{
	"inspect":   "symphony.knowledge.engine-descriptor.v2",
	"roundtrip": "symphony.graph.adapter-result.v1",
	"query":     "symphony.graph.adapter-result.v1",
}
var shvGraphAdapterInterfaceAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"inspect": true, "roundtrip": true, "query": true},
	"0.2.0-dev": {"inspect": true, "roundtrip": true, "query": true},
}
