// Code generated by tools/shv-interface-codegen/generate.cpp; DO NOT EDIT.
package knowledgeengine

const SHVSourceInterfaceVersion = "0.2.0-dev"
const shvSourceInterfaceDigest = "sha256:db0036a6de85f3701046ef99d2d5bd73bfaad12528dee40f0148fc7cf435ba62"

var shvSourceOutputs = map[string]string{
	"inspect":         "symphony.knowledge.engine-descriptor.v2",
	"source_plan":     "symphony.shv.source-plan.v1",
	"source_reduce":   "symphony.shv.source-transition.v1",
	"source_status":   "symphony.shv.source-status.v1",
	"capture_import":  "symphony.shv.source-capture.v1",
	"capture_compare": "symphony.shv.capture-comparison.v1",
	"graph_project":   "symphony.graph.exchange.v1",
	"graph_validate":  "symphony.shv.source-graph-validation.v1",
}
var shvSourceAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"inspect": true, "source_plan": true, "source_reduce": true, "source_status": true, "capture_import": true, "capture_compare": true, "graph_project": true, "graph_validate": true},
	"0.2.0-dev": {"inspect": true, "source_plan": true, "source_reduce": true, "source_status": true, "capture_import": true, "capture_compare": true, "graph_project": true, "graph_validate": true},
}
