// Code generated by shv-profile-engine/tools/generate_interface.py; DO NOT EDIT.
package knowledgeengine

const SHVProfileInterfaceVersion = "0.3.0-dev"
const shvProfileInterfaceDigest = "sha256:55d177fa9217292e115272f6d1bf88890686cf0b715889f4625ca8f62ef89514"

var shvProfileOutputs = map[string]string{
	"inspect":             "symphony.knowledge.engine-descriptor.v2",
	"profile_compile":     "symphony.shv.class-profile.v1",
	"mapping_diagnose":    "symphony.shv.mapping-diagnostics.v1",
	"universe_build":      "symphony.shv.universe.v1",
	"universe_bind":       "symphony.shv.universe-binding.v1",
	"extraction_diagnose": "symphony.shv.extraction-diagnostics.v1",
	"references_analyze":  "symphony.shv.reference-analysis.v1",
}
var shvProfileAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"inspect": true, "profile_compile": true, "mapping_diagnose": true, "universe_build": true, "universe_bind": true},
	"0.2.0-dev": {"inspect": true, "profile_compile": true, "mapping_diagnose": true, "universe_build": true, "universe_bind": true, "extraction_diagnose": true, "references_analyze": true},
	"0.3.0-dev": {"inspect": true, "profile_compile": true, "mapping_diagnose": true, "universe_build": true, "universe_bind": true, "extraction_diagnose": true, "references_analyze": true},
}
