// Code generated by tools/shv-interface-codegen/generate.py; DO NOT EDIT.
package knowledgeengine

const SHVPublicationInterfaceVersion = "0.4.0-dev"
const shvPublicationInterfaceDigest = "sha256:d41154e49e9a93356b7e7da1a581338ecc119fe1ba221eef9e800bbfcd68f047"

var shvPublicationOutputs = map[string]string{
	"inspect":            "symphony.knowledge.engine-descriptor.v2",
	"publication_plan":   "symphony.shv.publication-plan.v1",
	"publication_reduce": "symphony.shv.publication-transition.v1",
	"publication_status": "symphony.shv.publication-status.v1",
}
var shvPublicationAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"inspect": true, "publication_plan": true, "publication_reduce": true, "publication_status": true},
	"0.2.0-dev": {"inspect": true, "publication_plan": true, "publication_reduce": true, "publication_status": true},
	"0.3.0-dev": {"inspect": true, "publication_plan": true, "publication_reduce": true, "publication_status": true},
	"0.4.0-dev": {"inspect": true, "publication_plan": true, "publication_reduce": true, "publication_status": true},
}
