// Code generated by owner_codegen.cpp for shv-pdf-adapter; DO NOT EDIT.
package knowledgeengine

const SHVPDFInterfaceVersion = "0.3.0-dev"
const shvPDFInterfaceDigest = "sha256:c2167a75be02d08f4089e81fd82335d0aa8dd9f7ac80cb94be99f334b7ce2fdd"

var shvPDFInterfaceOutputs = map[string]string{
	"inspect":        "symphony.knowledge.engine-descriptor.v2",
	"extract":        "symphony.shv.pdf-extraction.v1",
	"graph_project":  "symphony.graph.exchange.v1",
	"graph_validate": "symphony.shv.pdf-graph-validation.v1",
}
var shvPDFInterfaceAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"inspect": true, "extract": true},
	"0.2.0-dev": {"inspect": true, "extract": true, "graph_project": true, "graph_validate": true},
	"0.3.0-dev": {"inspect": true, "extract": true, "graph_project": true, "graph_validate": true},
}
