// Code generated by owner_codegen.cpp for sniv-engine; DO NOT EDIT.
package knowledgeengine

const SNIVAdministrationInterfaceVersion = "0.1.0-dev"
const snivAdministrationInterfaceDigest = "sha256:58212500554975689990e549244fd10833950fb07f7190524c38eb1832395990"

var snivAdministrationInterfaceOutputs = map[string]string{
	"identity_validate": "symphony.sniv.identity-validate.v1",
}
var snivAdministrationInterfaceAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"identity_validate": true},
}

var snivAdministrationInterfaceResources = map[string]string{
	"admin.schema.json":    "sha256:9ea9d105f8d771a68589104a58355217ba4da73112833e3981591b825e7ef784",
	"admin.templates.json": "sha256:21a76f0f56946566c27e56963dc1b2d7fd1ab96638a044cf5bad6edb341f537c",
}
