// Code generated by owner_codegen.cpp for snrv-engine; DO NOT EDIT.
package knowledgeengine

const SNRVAdministrationInterfaceVersion = "0.1.0-dev"
const snrvAdministrationInterfaceDigest = "sha256:5b2a9ec7d8a423a9a2fb8eefe2eac4dbdff675e257a34a141a8b432d7d5bb7b1"

var snrvAdministrationInterfaceOutputs = map[string]string{
	"resources_validate": "symphony.snrv.resources-validate.v1",
}
var snrvAdministrationInterfaceAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"resources_validate": true},
}

var snrvAdministrationInterfaceResources = map[string]string{
	"admin.schema.json":    "sha256:883d38a1355025dadcb0d9938e4b15d601545ee6abf42682aeec36665af2ca9d",
	"admin.templates.json": "sha256:3c1aaf420a154413c4898b4e0005f6e93572f681479f8747da5c64acfa279b75",
}
