// Code generated by owner_codegen.cpp for snv-local-observer; DO NOT EDIT.
package knowledgeengine

const SNVObserverAdministrationInterfaceVersion = "0.1.0-dev"
const snvObserverAdministrationInterfaceDigest = "sha256:82ad79d27804ab494f77c71e213d8141acab1da156e472894a67ade1433db60a"

var snvObserverAdministrationInterfaceOutputs = map[string]string{
	"observe": "symphony.snv.local-observe.v1",
}
var snvObserverAdministrationInterfaceAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"observe": true},
}

var snvObserverAdministrationInterfaceResources = map[string]string{
	"admin.schema.json":    "sha256:80d498a28c4fa3a449c60768c77ff95a347811e5a02c054cd9d9d6a88ee01450",
	"admin.templates.json": "sha256:bd2f0a1e33cb49b0774a9e1b8685782862b642853c24d9604380234eaf7ea951",
}
