// Code generated by owner_codegen.cpp for snv-engine; DO NOT EDIT.
package knowledgeengine

const SNVAdministrationInterfaceVersion = "0.1.0-dev"
const snvAdministrationInterfaceDigest = "sha256:bc8a9d1bf69439be192522be6d351a798132f013d42d812785583c66d1fdb57f"

var snvAdministrationInterfaceOutputs = map[string]string{
	"snv_inspect":       "symphony.snv.inspect.v1",
	"snv_evidence_plan": "symphony.snv.evidence-plan.v1",
	"snv_state_plan":    "symphony.snv.state-plan.v1",
	"snv_state_reduce":  "symphony.snv.state-transition.v1",
}
var snvAdministrationInterfaceAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"snv_inspect": true, "snv_evidence_plan": true, "snv_state_plan": true, "snv_state_reduce": true},
}

var snvAdministrationInterfaceResources = map[string]string{
	"admin.schema.json":                    "sha256:8268fa1d6194835db4c1efe75b41d915b0489c6cb934b7070e11dc234401e7f4",
	"admin.templates.json":                 "sha256:c95694691525e35ec1c59b9defc70db8fd804e5e8a28621da879f9d98dec78c4",
	"snv_evidence_plan.result.schema.json": "sha256:b93b5663d5085247434721c5474843d9b6e1db3899f6fa3aa73383eeddb69c5d",
	"snv_evidence_plan.schema.json":        "sha256:ff285e931c0f16d19cc084a6408ab87c3af98afbd22e3197e993e42e6874575d",
	"snv_inspect.result.schema.json":       "sha256:18af5bc3d2177ee36ea1ac36bbfac7de87feb0c48d0cac76a46b6066b2610234",
	"snv_inspect.schema.json":              "sha256:573f1c80b657becfd7d332b814a7dc268cde2534a755b08a0998e6ba62e139af",
	"snv_state_plan.result.schema.json":    "sha256:899c45f600e6a8c3a46f049f98e297b568e76dac65a5dab1f7673adbefcd66c6",
	"snv_state_plan.schema.json":           "sha256:7b6ee9e4ebc6e0e89b05ee356148b786da037d331edab17c7eee935eba514ec0",
	"snv_state_reduce.result.schema.json":  "sha256:eda3919d3863377042db210505f197d20a23b925739cebadf3222e29bdda5252",
	"snv_state_reduce.schema.json":         "sha256:f4a2404b2cce6dd1cd8cab70a913614295f0a38714307d5213e245633d5517fe",
	"state-proposal.schema.json":           "sha256:6f31f0ea5cf004c2fb42ba3e80e29b3c662295f3d71485e817f73476955d4dc1",
}
