// Code generated by owner_codegen.cpp for sqav-request-engine; DO NOT EDIT.
package knowledgeengine

const SQAVRequestInterfaceVersion = "0.1.0-dev"
const sqavRequestInterfaceDigest = "sha256:07a29f4c37e9cf154a3265f6796bbab31508f6be54b06c776699f04eac5a7243"

var sqavRequestInterfaceOutputs = map[string]string{
	"request_validate": "symphony.sqav.request-validation.v1",
}
var sqavRequestInterfaceAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"request_validate": true},
}

var sqavRequestInterfaceResources = map[string]string{
	"request.schema.json":    "sha256:0b6eab2f1434ed2ea67d2fbb2f9c040bc1a63258952addacd12d48d51c941769",
	"request.templates.json": "sha256:be557da101b5299bfb55e8a7cbb58f01cb628ae49cf494b0e4be91cabd48da82",
}
