// Code generated by owner_codegen.cpp for sqav-attempt-engine; DO NOT EDIT.
package knowledgeengine

const SQAVAttemptInterfaceVersion = "0.1.0-dev"
const sqavAttemptInterfaceDigest = "sha256:8bc309d4c0256ba9c293a9b231a39c0c42ee15fd6f0c33bf985ac25a687f00f6"

var sqavAttemptInterfaceOutputs = map[string]string{
	"attempts_inspect": "symphony.sqav.attempts-inspect.v1",
}
var sqavAttemptInterfaceAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"attempts_inspect": true},
}

var sqavAttemptInterfaceResources = map[string]string{
	"admin.schema.json":    "sha256:6b4a9b395b515b61bebb97d22e43388c3dcacb7bf4e4e9f2b537fe83c86faced",
	"admin.templates.json": "sha256:d7d2517a18df9e445f96c4b64f44a03da7163d2b2421da2859bdb21dc2e3fc8b",
}
