// Code generated by owner_codegen.cpp for sqdv-checkpoint-engine; DO NOT EDIT.
package knowledgeengine

const SQDVCheckpointInterfaceVersion = "0.1.0-dev"
const sqdvCheckpointInterfaceDigest = "sha256:d41d81df09f9f4fc15d0e65771c40b97efd9d2d6a5909e0433c34f6ae965485f"

var sqdvCheckpointInterfaceOutputs = map[string]string{
	"checkpoint_inspect": "symphony.sqdv.checkpoint-inspect.v1",
}
var sqdvCheckpointInterfaceAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"checkpoint_inspect": true},
}

var sqdvCheckpointInterfaceResources = map[string]string{
	"admin.schema.json":    "sha256:f9ddac0b4249983efe9e9cc1749d5acb7145c3a1c695a633fcb25bda4a73db6b",
	"admin.templates.json": "sha256:0dc12a19925318f1a0abb44a8db5a9956843d9c772abd4e1b47cc7a2dacf10e9",
}
