// Code generated by owner_codegen.cpp for sqfv-flow-engine; DO NOT EDIT.
package knowledgeengine

const SQFVFlowInterfaceVersion = "0.1.0-dev"
const sqfvFlowInterfaceDigest = "sha256:6694c85d77adc186bc8bd24a82a19b646475ccd84a8ed3f7d3c145d959d5b70f"

var sqfvFlowInterfaceOutputs = map[string]string{
	"flow_validate": "symphony.sqfv.flow-validate.v1",
}
var sqfvFlowInterfaceAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"flow_validate": true},
}

var sqfvFlowInterfaceResources = map[string]string{
	"admin.schema.json":    "sha256:48deabe096bab6a62cc36f13997d0c907c484e06f9cb1e1d47fa3fbc73f19294",
	"admin.templates.json": "sha256:a87ed54a7aab74dcd57c14904008abf33a41043fa3849b903c922cd258d3d374",
}
