// Code generated by owner_codegen.cpp for sqmv-metadata-engine; DO NOT EDIT.
package knowledgeengine

const SQMVMetadataInterfaceVersion = "0.1.0-dev"
const sqmvMetadataInterfaceDigest = "sha256:9d9c24c53086bff63add07a2574bcdbd8846eb4b55c5455b42a4ff26df78b9f5"

var sqmvMetadataInterfaceOutputs = map[string]string{
	"metadata_validate": "symphony.sqmv.metadata-validate.v1",
	"metadata_inspect":  "symphony.sqmv.metadata-inspect.v1",
}
var sqmvMetadataInterfaceAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"metadata_validate": true, "metadata_inspect": true},
}

var sqmvMetadataInterfaceResources = map[string]string{
	"admin.schema.json":    "sha256:0abd29fb87b76848d181b458bbdb054bddd92f33f089a0d29bd3691066a12fee",
	"admin.templates.json": "sha256:f61292881a54cd66ca2be0f9251cf2949acea90a39b504aa9e5a1e0154143e87",
}
