// Code generated by owner_codegen.cpp for sqpv-inspection-engine; DO NOT EDIT.
package knowledgeengine

const SQPVInspectionInterfaceVersion = "0.1.0-dev"
const sqpvInspectionInterfaceDigest = "sha256:cd1bce45a21c5151b7af86011a2947749660d17b30702a8f27936740a6cd9376"

var sqpvInspectionInterfaceOutputs = map[string]string{
	"store_inspect": "symphony.sqpv.store-inspect.v1",
}
var sqpvInspectionInterfaceAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"store_inspect": true},
}

var sqpvInspectionInterfaceResources = map[string]string{
	"admin.schema.json":    "sha256:067752ae471d6bd78131c7e4d3e411f3ec955202daeec9f04bb9b36750df9750",
	"admin.templates.json": "sha256:bf9bc4baf5e3fdb0db697c623024e467bc37ad9ca9724ce3bd2f0880ee7550d6",
}
