// Code generated by owner_codegen.cpp for sqtv-conversion-engine; DO NOT EDIT.
package knowledgeengine

const SQTVConversionInterfaceVersion = "0.1.0-dev"
const sqtvConversionInterfaceDigest = "sha256:e3a711bbb26a4683082be8be8132c9fbbbeecd56ca0cdd634525b1254c6ad4c6"

var sqtvConversionInterfaceOutputs = map[string]string{
	"conversion_validate": "symphony.sqtv.conversion-validate.v1",
}
var sqtvConversionInterfaceAdmission = map[string]map[string]bool{
	"0.1.0-dev": {"conversion_validate": true},
}

var sqtvConversionInterfaceResources = map[string]string{
	"admin.schema.json":    "sha256:86c6d1ac9dcc236dab02939aae8681ce64817c4157f72b998d2a2705347e8bb0",
	"admin.templates.json": "sha256:81f5e1f62d40748ef123e7066cc2ec5cb8f8aebe43401fc58a4d93fe4c087add",
}
