// Generated by owner_codegen.cpp; do not edit.
#pragma once
#include "symphony/knowledge/engine/operation.hpp"
namespace symphony::sqfv::administration {
namespace engine = symphony::knowledge::engine;
inline constexpr auto version = "0.1.0-dev";
inline std::vector<engine::OperationSpec> interface_operations() { return {
  {"engop:symphony:sqfv-flow.validate", "flow_validate", "implemented", false, true, {"ssfv:symphony:sqfv-flow-engine"}, {"validate"}, "qxctl_required", "symphony.sqfv.flow-validate-input.v1", "symphony.sqfv.flow-validate.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
}; }
}
