// Generated by owner_codegen.cpp; do not edit.
#pragma once
#include "symphony/knowledge/engine/operation.hpp"
namespace symphony::sqpv::administration {
namespace engine = symphony::knowledge::engine;
inline constexpr auto version = "0.1.0-dev";
inline std::vector<engine::OperationSpec> interface_operations() { return {
  {"engop:symphony:sqpv-inspection.inspect", "store_inspect", "implemented", false, true, {"ssfv:symphony:sqpv-inspection-engine"}, {"inspect"}, "qxctl_required", "symphony.sqpv.store-inspect-input.v1", "symphony.sqpv.store-inspect.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
}; }
}
