// Generated by owner_codegen.cpp; do not edit.
#pragma once
#include "symphony/knowledge/engine/operation.hpp"
namespace symphony::sqav::request {
namespace engine = symphony::knowledge::engine;
inline constexpr auto version = "0.1.0-dev";
inline std::vector<engine::OperationSpec> interface_operations() { return {
  {"engop:symphony:sqav-request.validate", "request_validate", "implemented", false, true, {"ssfv:symphony:sqav-request-engine"}, {"validate"}, "qxctl_required", "symphony.sqav.request-validation-input.v1", "symphony.sqav.request-validation.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
}; }
}
