// Generated by tools/generate_interface.py; do not edit.
#pragma once
#include <array>
namespace symphony::knowledge::shv_profile {
inline constexpr auto version = "0.3.0-dev";
inline constexpr auto embedded_kernel_version = "0.3.0-dev";
struct InterfaceOperation { const char *name; const char *input; const char *output; const char *interaction; };
inline constexpr std::array<InterfaceOperation, 7> interface_operations = {{
  {"inspect", "symphony.shv.inspect-input.v1", "symphony.knowledge.engine-descriptor.v2", "inspect"},
  {"profile_compile", "symphony.shv.profile-compile-input.v1", "symphony.shv.class-profile.v1", "invoke"},
  {"mapping_diagnose", "symphony.shv.mapping-diagnose-input.v1", "symphony.shv.mapping-diagnostics.v1", "query"},
  {"universe_build", "symphony.shv.universe-build-input.v1", "symphony.shv.universe.v1", "invoke"},
  {"universe_bind", "symphony.shv.universe-bind-input.v1", "symphony.shv.universe-binding.v1", "invoke"},
  {"extraction_diagnose", "symphony.shv.extraction-diagnose-input.v1", "symphony.shv.extraction-diagnostics.v1", "query"},
  {"references_analyze", "symphony.shv.references-analyze-input.v1", "symphony.shv.reference-analysis.v1", "query"},
}};
}
