"""Generate profile-owner mechanical metadata; no semantic implementation generation."""
from pathlib import Path
import argparse,json,re,subprocess,hashlib
ROOT=Path(__file__).resolve().parents[3]
MODULE='modules/shv-profile-engine'
def read(p):
 def pairs(items):
  d={}
  for k,v in items:
   if k in d:raise ValueError('duplicate JSON key: '+k)
   d[k]=v
  return d
 return json.loads(p.read_text(),object_pairs_hook=pairs)
def validate(d,root=ROOT):
 assert set(d)=={'protocol','module_id','engine_id','current_version','embedded_kernel_version','contract_versions','releases','operations','schemas','companions'}
 assert d['protocol']=='symphony.shv.profile-owner-interface.v1' and d['module_id']=='shv-profile-engine' and d['engine_id']=='symphony-shv-profile'
 assert d['current_version']=='0.3.0-dev' and d['embedded_kernel_version']=='0.3.0-dev'
 assert d['contract_versions']==['knowledge/shv/PROFILES.md@v1']
 assert set(d['releases'])=={'0.1.0-dev','0.2.0-dev','0.3.0-dev'}
 assert hashlib.sha256((root/MODULE/'tests/fixtures/interface-history.v1.json').read_bytes()).hexdigest()=='9381ad350d97731ac211dd30284f92995fc92aad729a9ad06a8057d10444ff5e','frozen history changed'
 hist=read(root/MODULE/'tests/fixtures/interface-history.v1.json')['descriptors'];ops=d['operations'];names=[o['operation_name']for o in ops];assert len(names)==len(set(names))
 for version,old in hist.items():
  assert d['releases'][version]==[o['operation_name']for o in old['operations']]
  assert [o for o in ops if o['operation_name']in d['releases'][version]]==old['operations'],'historical metadata changed'
 assert d['releases']['0.3.0-dev']==names and names==d['releases']['0.2.0-dev']
 assert len(d['schemas'])==len(set(d['schemas'])) and len(d['companions'])==len(set(d['companions']))
 assert d['schemas']==[MODULE+'/schemas/v1/profile.schema.json',MODULE+'/schemas/v1/profile.templates.json']
 assert d['companions']==['knowledge/shv/PROFILES.md']
 for path in d['schemas']+d['companions']:
  p=Path(path);assert not p.is_absolute() and '..'not in p.parts and p.as_posix()==path
  q=root/p;assert q.is_file() and not q.is_symlink() and q.resolve().is_relative_to(root.resolve())
 for path in d['schemas']:
  doc=read(root/path)
  def visit(x):
   if isinstance(x,dict):
    if '$ref'in x:
     ref=x['$ref'];assert ref.startswith('#/'),'nonlocal schema reference'
     target=doc
     for part in ref[2:].split('/'):target=target[part.replace('~1','/').replace('~0','~')]
    for v in x.values():visit(v)
   elif isinstance(x,list):
    for v in x:visit(v)
  visit(doc)
 return d

def outputs(d):
 q=lambda x:json.dumps(x,ensure_ascii=True);ops=d['operations'];raw=json.dumps(d,sort_keys=True,separators=(',',':')).encode();digest='sha256:'+hashlib.sha256(raw).hexdigest()
 cpp='// Generated by tools/generate_interface.py; do not edit.\n#pragma once\n#include <array>\nnamespace symphony::knowledge::shv_profile {\ninline constexpr auto version = '+q(d['current_version'])+';\ninline constexpr auto embedded_kernel_version = '+q(d['embedded_kernel_version'])+';\nstruct InterfaceOperation { const char *name; const char *input; const char *output; const char *interaction; };\ninline constexpr std::array<InterfaceOperation, '+str(len(ops))+'> interface_operations = {{\n'
 for o in ops:cpp+='  {'+', '.join(q(o[k])for k in ['operation_name','input_protocol','output_protocol'])+', '+q(o['administrative_interactions'][0])+'},\n'
 cpp+='}};\n}\n'
 go='// Code generated by shv-profile-engine/tools/generate_interface.py; DO NOT EDIT.\npackage knowledgeengine\n\nconst SHVProfileInterfaceVersion = '+q(d['current_version'])+'\nconst shvProfileInterfaceDigest = '+q(digest)+'\nvar shvProfileOutputs = map[string]string{\n'
 for o in ops:go+=q(o['operation_name'])+': '+q(o['output_protocol'])+',\n'
 go+='}\nvar shvProfileAdmission = map[string]map[string]bool{\n'
 for v,names in d['releases'].items():go+=q(v)+': {'+', '.join(q(n)+': true'for n in names)+'},\n'
 go+='}\n';go=subprocess.check_output(['gofmt'],input=go.encode()).decode()
 cm='# Generated by tools/generate_interface.py; do not edit.\nset(SHV_PROFILE_VERSION "'+d['current_version'].removesuffix('-dev')+'")\n'
 for key,var in [('schemas','SHV_PROFILE_SCHEMA_FILES'),('companions','SHV_PROFILE_COMPANIONS')]:cm+='set('+var+'\n'+''.join(' "${SYMPHONY_REPOSITORY_ROOT}/'+p+'"\n'for p in d[key])+')\n'
 return {MODULE+'/src/interface.generated.hpp':cpp,'tools/qxctl/internal/knowledgeengine/shv_profile_interface_generated.go':go,'cmake/ShvProfileInterface.generated.cmake':cm}
def main():
 p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args();d=validate(read(ROOT/MODULE/'OWNER-INTERFACE.json'))
 for path,body in outputs(d).items():
  out=ROOT/path
  if a.check:assert out.read_text()==body,'generated drift: '+path
  else:out.write_text(body)
 print('profile interface: checked'if a.check else 'profile interface: generated')
if __name__=='__main__':main()
