// Generated by owner_codegen.py; do not edit.
#pragma once
#include "symphony/knowledge/engine/operation.hpp"
namespace symphony::graph {
namespace engine = symphony::knowledge::engine;
#ifdef SYMPHONY_SHV_GRAPH_ADAPTER_EMBEDDED_PREVIOUS
inline constexpr auto version = "0.1.0-dev";
#else
inline constexpr auto version = "0.2.0-dev";
#endif
inline std::vector<engine::OperationSpec> interface_operations() { return {
  {"engop:symphony:shv-graph-adapter.inspect", "inspect", "implemented", false, true, {"ssfv:symphony:shv-graph-adapter"}, {"inspect"}, "qxctl_required", "symphony.graph.adapter-inspect-input.v1", "symphony.knowledge.engine-descriptor.v2", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:shv-graph-adapter.roundtrip", "roundtrip", "implemented", false, true, {"ssfv:symphony:shv-graph-adapter"}, {"invoke"}, "qxctl_required", "symphony.graph.adapter-roundtrip-input.v1", "symphony.graph.adapter-result.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
  {"engop:symphony:shv-graph-adapter.query", "query", "implemented", false, true, {"ssfv:symphony:shv-graph-adapter"}, {"query"}, "qxctl_required", "symphony.graph.adapter-query-input.v1", "symphony.graph.adapter-result.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
}; }
}
