// Generated by owner_codegen.cpp; do not edit.
#pragma once
#include "symphony/knowledge/engine/operation.hpp"
namespace symphony::sqtv::administration {
namespace engine = symphony::knowledge::engine;
inline constexpr auto version = "0.1.0-dev";
inline std::vector<engine::OperationSpec> interface_operations() { return {
  {"engop:symphony:sqtv-conversion.validate", "conversion_validate", "implemented", false, true, {"ssfv:symphony:sqtv-conversion-engine"}, {"validate"}, "qxctl_required", "symphony.sqtv.conversion-validate-input.v1", "symphony.sqtv.conversion-validate.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
}; }
}
