# Generated by owner_codegen.cpp for sbv-engine; do not edit.
set(SBV_VERSION "0.23.0")
set(SBV_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sbv-engine/schemas/v1/admin.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sbv-engine/schemas/v1/admin.templates.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sbv-engine/schemas/v1/result.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sbv-engine/schemas/v1/pointer-stream.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sbv-engine/schemas/v1/partitioned-result.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sbv-engine/schemas/v1/result-page.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sbv-engine/schemas/v1/node-stream.schema.json"
)
set(SBV_COMPANIONS
)
