# Generated by owner_codegen.cpp for sciv-engine; do not edit.
set(SCIV_VERSION "0.1.0")
set(SCIV_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sciv-engine/schemas/v1/sciv-evidence.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sciv-engine/schemas/v1/sciv-evidence.template.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sciv-engine/schemas/v1/sciv-result.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sciv-engine/schemas/v1/sciv-transition-result.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sciv-engine/schemas/v1/sciv-transition.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sciv-engine/schemas/v1/sciv-transition.template.json"
)
set(SCIV_COMPANIONS
)
