# Generated by owner_codegen.cpp for scnv-engine; do not edit.
set(SCNV_VERSION "0.1.0")
set(SCNV_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/scnv-engine/schemas/v1/admin.templates.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/scnv-engine/schemas/v1/names-result.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/scnv-engine/schemas/v1/names.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/scnv-engine/schemas/v1/resolve-result.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/scnv-engine/schemas/v1/resolve.schema.json"
)
set(SCNV_COMPANIONS
)
