# Generated by modules/scv-engine/tools/generate_interface.py; DO NOT EDIT.
# Owner interface SHA-256: sha256:f83d5d40ed3b34717736725a1816426fae8021cf32aaf126d6164c2a6a972330
set(SCV_INTERFACE_VERSION "0.9.0-dev")
set(SCV_INTERFACE_DOMAINS scv schv scev schv-aws schv-azure schv-do schv-gcp scev-cf)
set(SCV_INTERFACE_SCHEMA_FILES
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/administration.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/bundle.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/capture-index.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/capture.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/composition.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/connection-operation.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/corpus-operation.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/corpus.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/engine-descriptor-v2.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/graph-operation.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/interpretation-input.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/interpretation-profile.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/knowledge-graph.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/obligation.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/owner-interface.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/profile-preparation.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/provider-coverage.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/provider-interpretation.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/provider-pack.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/qxctl-error.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/schema-catalog.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/schema-discovery.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/scv-artifact.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/scv-composition-workflow.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/scv-obligation-link.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/scv-workflow.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/source-operation.schema.json"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/schemas/v1/source.schema.json"
)
set(SCV_INTERFACE_COMPANION_FILES
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/SOURCE-KNOWLEDGE.md"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/CORPUS.md"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/INTERPRETATION.md"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/AGENT-WORKFLOWS.md"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/COVERAGE.md"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/PROVIDER-PACKS.md"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/COMPOSITION.md"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/OWNER-INTERFACE.md"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/COMPOSITION-WORKFLOWS.md"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/OBLIGATIONS.md"
    "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/BUNDLES.md"
)
set(SCV_INTERFACE_MANIFEST "${SYMPHONY_REPOSITORY_ROOT}/knowledge/scv/OWNER-INTERFACE.json")
