# Generated by owner_codegen.cpp for shv-graph-adapter; do not edit.
set(SHV_OWNER_VERSION "0.2.0")
set(SHV_OWNER_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/shv-graph-adapter/schemas/v1/graph-adapter.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/shv-graph-adapter/schemas/v1/graph-adapter.templates.json"
)
set(SHV_OWNER_COMPANIONS
)
