# Generated by owner_codegen.py for shv-engine; do not edit.
set(SHV_OWNER_VERSION "0.4.0")
set(SHV_OWNER_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/shv-engine/schemas/v1/shv.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/shv-engine/schemas/v1/shv.templates.json"
)
set(SHV_OWNER_COMPANIONS
 "${SYMPHONY_REPOSITORY_ROOT}/knowledge/shv/DOCUMENT-INGESTION.md"
)
