# Generated by owner_codegen.cpp for shv-pdf-adapter; do not edit.
set(SHV_OWNER_VERSION "0.3.0")
set(SHV_OWNER_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/shv-pdf-adapter/schemas/v1/pdf.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/shv-pdf-adapter/schemas/v1/pdf.templates.json"
)
set(SHV_OWNER_COMPANIONS
 "${SYMPHONY_REPOSITORY_ROOT}/knowledge/shv/PDF-ADAPTER.md"
)
