# Generated by tools/generate_interface.py; do not edit.
set(SHV_PROFILE_VERSION "0.3.0")
set(SHV_PROFILE_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/shv-profile-engine/schemas/v1/profile.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/shv-profile-engine/schemas/v1/profile.templates.json"
)
set(SHV_PROFILE_COMPANIONS
 "${SYMPHONY_REPOSITORY_ROOT}/knowledge/shv/PROFILES.md"
)
