# Generated by owner_codegen.cpp for shv-partition-engine; do not edit.
set(SHV_OWNER_VERSION "0.4.0")
set(SHV_OWNER_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/shv-partition-engine/schemas/v1/partition.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/shv-partition-engine/schemas/v1/partition.templates.json"
)
set(SHV_OWNER_COMPANIONS
 "${SYMPHONY_REPOSITORY_ROOT}/knowledge/shv/PARTITIONS.md"
)
