# Generated by tools/shv-interface-codegen/generate.py; do not edit.
set(SHV_OWNER_VERSION "0.4.0")
set(SHV_OWNER_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/shv-publication-engine/schemas/v1/publication.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/shv-publication-engine/schemas/v1/publication.templates.json"
)
set(SHV_OWNER_COMPANIONS
 "${SYMPHONY_REPOSITORY_ROOT}/knowledge/shv/PUBLICATION.md"
)
