# Generated by owner_codegen.py for shv-graph-duckdb-connector; do not edit.
set(SHV_OWNER_VERSION "0.4.0")
set(SHV_OWNER_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/shv-graph-duckdb-connector/schemas/v1/graph-store.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/shv-graph-duckdb-connector/schemas/v1/graph-store.templates.json"
)
set(SHV_OWNER_COMPANIONS
 "${SYMPHONY_REPOSITORY_ROOT}/knowledge/shv/GRAPH-STORE.md"
)
