# Generated by tools/shv-interface-codegen/generate.cpp; do not edit.
set(SHV_OWNER_VERSION "0.2.0")
set(SHV_OWNER_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/shv-source-engine/schemas/v1/source.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/shv-source-engine/schemas/v1/source.templates.json"
)
set(SHV_OWNER_COMPANIONS
 "${SYMPHONY_REPOSITORY_ROOT}/knowledge/shv/SOURCES.md"
)
