# Generated by owner_codegen.cpp for sniv-engine; do not edit.
set(SNIV_VERSION "0.1.0")
set(SNIV_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sniv-engine/schemas/v1/admin.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sniv-engine/schemas/v1/admin.templates.json"
)
set(SNIV_COMPANIONS
)
