# Generated by owner_codegen.cpp for snrv-engine; do not edit.
set(SNRV_VERSION "0.1.0")
set(SNRV_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/snrv-engine/schemas/v1/admin.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/snrv-engine/schemas/v1/admin.templates.json"
)
set(SNRV_COMPANIONS
)
