# Generated by owner_codegen.cpp for snv-engine; do not edit.
set(SNV_VERSION "0.1.0")
set(SNV_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/snv-engine/schemas/v1/admin.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/snv-engine/schemas/v1/admin.templates.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/snv-engine/schemas/v1/snv_evidence_plan.result.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/snv-engine/schemas/v1/snv_evidence_plan.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/snv-engine/schemas/v1/snv_inspect.result.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/snv-engine/schemas/v1/snv_inspect.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/snv-engine/schemas/v1/snv_state_plan.result.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/snv-engine/schemas/v1/snv_state_plan.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/snv-engine/schemas/v1/snv_state_reduce.result.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/snv-engine/schemas/v1/snv_state_reduce.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/snv-engine/schemas/v1/state-proposal.schema.json"
)
set(SNV_COMPANIONS
)
