# Generated by owner_codegen.cpp for snv-local-observer; do not edit.
set(SNV_OBSERVER_VERSION "0.1.0")
set(SNV_OBSERVER_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/snv-local-observer/schemas/v1/admin.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/snv-local-observer/schemas/v1/admin.templates.json"
)
set(SNV_OBSERVER_COMPANIONS
)
