# Generated by owner_codegen.cpp for sqav-attempt-engine; do not edit.
set(SQAV_ATTEMPT_VERSION "0.1.0")
set(SQAV_ATTEMPT_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sqav-attempt-engine/schemas/v1/admin.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sqav-attempt-engine/schemas/v1/admin.templates.json"
)
set(SQAV_ATTEMPT_COMPANIONS
)
