# Generated by owner_codegen.cpp for sqav-request-engine; do not edit.
set(SQAV_REQUEST_VERSION "0.1.0")
set(SQAV_REQUEST_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sqav-request-engine/schemas/v1/request.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sqav-request-engine/schemas/v1/request.templates.json"
)
set(SQAV_REQUEST_COMPANIONS
)
