# Generated by owner_codegen.cpp for sqdv-checkpoint-engine; do not edit.
set(SQDV_CHECKPOINT_VERSION "0.1.0")
set(SQDV_CHECKPOINT_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sqdv-checkpoint-engine/schemas/v1/admin.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sqdv-checkpoint-engine/schemas/v1/admin.templates.json"
)
set(SQDV_CHECKPOINT_COMPANIONS
)
