# Generated by owner_codegen.cpp for sqfv-flow-engine; do not edit.
set(SQFV_FLOW_VERSION "0.1.0")
set(SQFV_FLOW_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sqfv-flow-engine/schemas/v1/admin.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sqfv-flow-engine/schemas/v1/admin.templates.json"
)
set(SQFV_FLOW_COMPANIONS
)
