# Generated by owner_codegen.cpp for sqmv-metadata-engine; do not edit.
set(SQMV_METADATA_VERSION "0.1.0")
set(SQMV_METADATA_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sqmv-metadata-engine/schemas/v1/admin.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sqmv-metadata-engine/schemas/v1/admin.templates.json"
)
set(SQMV_METADATA_COMPANIONS
)
