# Generated by owner_codegen.cpp for sqpv-inspection-engine; do not edit.
set(SQPV_INSPECTION_VERSION "0.1.0")
set(SQPV_INSPECTION_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sqpv-inspection-engine/schemas/v1/admin.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sqpv-inspection-engine/schemas/v1/admin.templates.json"
)
set(SQPV_INSPECTION_COMPANIONS
)
