# Generated by owner_codegen.cpp for sqtv-conversion-engine; do not edit.
set(SQTV_CONVERSION_VERSION "0.1.0")
set(SQTV_CONVERSION_SCHEMA_FILES
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sqtv-conversion-engine/schemas/v1/admin.schema.json"
 "${SYMPHONY_REPOSITORY_ROOT}/modules/sqtv-conversion-engine/schemas/v1/admin.templates.json"
)
set(SQTV_CONVERSION_COMPANIONS
)
