if(NOT DEFINED _files)
  message(FATAL_ERROR "receipt-v2 uninstall requires an exact configured file list")
endif()

list(LENGTH _files _file_count)
if(_file_count LESS 2)
  message(FATAL_ERROR "receipt-v2 uninstall file list is incomplete")
endif()
math(EXPR _owned_count "${_file_count} - 1")
list(GET _files -1 _receipt_relative)
set(_receipt_path "${INSTALL_PREFIX}/${_receipt_relative}")

if(IS_SYMLINK "${_receipt_path}" OR IS_DIRECTORY "${_receipt_path}")
  message(FATAL_ERROR "receipt-v2 uninstall requires a no-follow regular receipt: ${_receipt_path}")
endif()

if(NOT EXISTS "${_receipt_path}")
  foreach(_index RANGE 0 ${_owned_count})
    if(_index EQUAL _owned_count)
      break()
    endif()
    list(GET _files ${_index} _relative)
    set(_path "${INSTALL_PREFIX}/${_relative}")
    if(IS_SYMLINK "${_path}" OR EXISTS "${_path}")
      message(FATAL_ERROR
        "receipt-v2 is absent while a configured owned path remains: ${_path}")
    endif()
  endforeach()
  return()
endif()

file(READ "${_receipt_path}" _receipt_json LIMIT 262145)
string(LENGTH "${_receipt_json}" _receipt_size)
if(_receipt_size GREATER 262144)
  message(FATAL_ERROR "receipt-v2 exceeds 262144 bytes")
endif()
string(JSON _protocol ERROR_VARIABLE _json_error GET "${_receipt_json}" protocol)
if(NOT _json_error STREQUAL "NOTFOUND" OR
   NOT _protocol STREQUAL "symphony.knowledge.install-receipt.v2")
  message(FATAL_ERROR "uninstall receipt is not the exact receipt-v2 protocol")
endif()
string(JSON _format_version GET "${_receipt_json}" format_version)
if(NOT _format_version EQUAL 2)
  message(FATAL_ERROR "uninstall receipt format version is not 2")
endif()
string(JSON _receipt_file_count LENGTH "${_receipt_json}" files)
if(NOT _receipt_file_count EQUAL _owned_count)
  message(FATAL_ERROR
    "uninstall receipt owns ${_receipt_file_count} files, expected ${_owned_count}")
endif()

set(_seen_receipt_paths "")
if(_receipt_file_count GREATER 0)
  math(EXPR _last_receipt_index "${_receipt_file_count} - 1")
  foreach(_index RANGE 0 ${_last_receipt_index})
    string(JSON _relative GET "${_receipt_json}" files ${_index} path)
    string(JSON _kind GET "${_receipt_json}" files ${_index} kind)
    string(JSON _size GET "${_receipt_json}" files ${_index} size)
    string(JSON _digest GET "${_receipt_json}" files ${_index} digest)
    string(LENGTH "${_digest}" _digest_length)
    string(FIND "${_relative}" "\\" _backslash)
    string(FIND "${_relative}" ";" _semicolon)
    if(_relative STREQUAL "" OR _relative MATCHES "(^/|(^|/)\\.\\.?(/|$)|//)" OR
       NOT _backslash EQUAL -1 OR NOT _semicolon EQUAL -1 OR
       (NOT _kind STREQUAL "regular" AND NOT _kind STREQUAL "executable") OR
       NOT _digest_length EQUAL 71 OR NOT _digest MATCHES "^sha256:[0-9a-f]+$")
      message(FATAL_ERROR "uninstall receipt contains an unsafe owned-file record")
    endif()
    list(FIND _seen_receipt_paths "${_relative}" _duplicate)
    list(FIND _files "${_relative}" _configured_index)
    if(NOT _duplicate EQUAL -1 OR _configured_index LESS 0 OR _configured_index EQUAL _owned_count)
      message(FATAL_ERROR "uninstall receipt file set does not match its configured package")
    endif()
    list(APPEND _seen_receipt_paths "${_relative}")

    set(_path "${INSTALL_PREFIX}/${_relative}")
    if(IS_SYMLINK "${_path}" OR IS_DIRECTORY "${_path}")
      message(FATAL_ERROR "refusing to uninstall a non-regular owned path: ${_path}")
    endif()
    if(EXISTS "${_path}")
      file(SIZE "${_path}" _actual_size)
      file(SHA256 "${_path}" _actual_sha)
      if(NOT _actual_size EQUAL _size OR NOT "sha256:${_actual_sha}" STREQUAL "${_digest}")
        message(FATAL_ERROR "receipt-v2 owned file content changed; refusing removal: ${_path}")
      endif()
    endif()
  endforeach()
endif()

foreach(_index RANGE 0 ${_owned_count})
  if(_index EQUAL _owned_count)
    break()
  endif()
  list(GET _files ${_index} _relative)
  list(FIND _seen_receipt_paths "${_relative}" _receipt_index)
  if(_receipt_index LESS 0)
    message(FATAL_ERROR "configured uninstall path is absent from receipt-v2: ${_relative}")
  endif()
endforeach()

# All remaining owned content is verified before mutation. Missing files are a
# resumable prior attempt. The receipt is intentionally the final list member.
foreach(_relative IN LISTS _files)
  set(_path "${INSTALL_PREFIX}/${_relative}")
  if(EXISTS "${_path}")
    file(REMOVE "${_path}")
    if(EXISTS "${_path}" OR IS_SYMLINK "${_path}")
      message(FATAL_ERROR "failed to remove installed file: ${_path}")
    endif()
  endif()
endforeach()
