include_guard(GLOBAL)

# Build-local package scripts run in an administrator-controlled, quiescent
# prefix. These checks reject existing redirections; they are not an openat/
# O_NOFOLLOW transaction against concurrent hostile filesystem mutation.
function(symphony_receipt_v2_relative_path path)
    string(LENGTH "${path}" length)
    if(path STREQUAL "" OR length GREATER 4096 OR
       path MATCHES "(^/|(^|/)\\.\\.?(/|$)|//|\\\\|;|/$)" OR
       path MATCHES "[\n\r\t]")
        message(FATAL_ERROR "unsafe receipt-v2 relative path: ${path}")
    endif()
    foreach(code RANGE 1 31)
        string(ASCII ${code} control)
        string(FIND "${path}" "${control}" position)
        if(NOT position EQUAL -1)
            message(FATAL_ERROR "receipt-v2 path contains a control character")
        endif()
    endforeach()
    string(ASCII 127 control)
    string(FIND "${path}" "${control}" position)
    if(NOT position EQUAL -1)
        message(FATAL_ERROR "receipt-v2 path contains a control character")
    endif()
endfunction()

function(symphony_receipt_v2_root input output)
    if(NOT IS_ABSOLUTE "${input}" OR IS_SYMLINK "${input}" OR
       (EXISTS "${input}" AND NOT IS_DIRECTORY "${input}"))
        message(FATAL_ERROR "receipt-v2 prefix must be an absolute non-symlink directory: ${input}")
    endif()
    # Resolve platform aliases such as /tmp before interpreting owned paths.
    set(existing "${input}")
    set(suffix "")
    while(NOT EXISTS "${existing}" AND NOT IS_SYMLINK "${existing}")
        get_filename_component(name "${existing}" NAME)
        get_filename_component(parent "${existing}" DIRECTORY)
        if(parent STREQUAL existing)
            message(FATAL_ERROR "receipt-v2 prefix has no existing ancestor: ${input}")
        endif()
        set(suffix "/${name}${suffix}")
        set(existing "${parent}")
    endwhile()
    file(REAL_PATH "${existing}" canonical)
    string(APPEND canonical "${suffix}")
    set(${output} "${canonical}" PARENT_SCOPE)
endfunction()

function(symphony_receipt_v2_no_follow root relative)
    symphony_receipt_v2_relative_path("${relative}")
    string(REPLACE "/" ";" components "${relative}")
    set(current "${root}")
    list(LENGTH components count)
    set(index 0)
    foreach(component IN LISTS components)
        math(EXPR index "${index} + 1")
        string(APPEND current "/${component}")
        if(IS_SYMLINK "${current}")
            message(FATAL_ERROR "receipt-v2 path traverses a symlink: ${current}")
        endif()
        if(index LESS count AND EXISTS "${current}" AND NOT IS_DIRECTORY "${current}")
            message(FATAL_ERROR "receipt-v2 path traverses a non-directory: ${current}")
        endif()
    endforeach()
endfunction()

function(symphony_receipt_v2_regular_file path)
    # Receipt packaging is supported only on macOS/Linux. CMake has no regular
    # file predicate; invoke the fixed native utility directly, without a shell,
    # before any potentially blocking read/hash of a FIFO, device, or socket.
    if(IS_SYMLINK "${path}")
        message(FATAL_ERROR "receipt-v2 requires a no-follow regular file: ${path}")
    endif()
    execute_process(COMMAND /bin/test -f "${path}"
        RESULT_VARIABLE regular OUTPUT_QUIET ERROR_QUIET TIMEOUT 2)
    if(NOT regular STREQUAL "0")
        message(FATAL_ERROR "receipt-v2 requires a regular file: ${path}")
    endif()
endfunction()

function(symphony_receipt_v2_json_string input output)
    string(REPLACE "\\" "\\\\" escaped "${input}")
    string(REPLACE "\"" "\\\"" escaped "${escaped}")
    string(REPLACE "\n" "\\n" escaped "${escaped}")
    string(REPLACE "\r" "\\r" escaped "${escaped}")
    string(REPLACE "\t" "\\t" escaped "${escaped}")
    string(ASCII 8 backspace)
    string(ASCII 12 formfeed)
    string(REPLACE "${backspace}" "\\b" escaped "${escaped}")
    string(REPLACE "${formfeed}" "\\f" escaped "${escaped}")
    # Match the receipt-v2 Go encoding/json digest convention.
    string(REPLACE "<" "\\u003c" escaped "${escaped}")
    string(REPLACE ">" "\\u003e" escaped "${escaped}")
    string(REPLACE "&" "\\u0026" escaped "${escaped}")
    string(ASCII 226 128 168 line_separator)
    string(ASCII 226 128 169 paragraph_separator)
    string(REPLACE "${line_separator}" "\\u2028" escaped "${escaped}")
    string(REPLACE "${paragraph_separator}" "\\u2029" escaped "${escaped}")
    set(${output} "\"${escaped}\"" PARENT_SCOPE)
endfunction()

# CMake's string(JSON) parser accepts comments, duplicate object members and
# trailing bytes. Validate the complete JSON grammar before using that parser
# for semantic decoding or digest normalization. Receipt member names are the
# schema's lowercase ASCII identifiers, including when escaped in the input.
function(symphony_receipt_v2_json_string_token input token_output rest_output)
    string(REGEX MATCH [=[^"([^"\\]|\\(["\\/bfnrt]|u[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]))*"]=] token "${input}")
    if(token STREQUAL "" OR token MATCHES "[\n\r\t]")
        message(FATAL_ERROR "receipt-v2 contains an invalid JSON string")
    endif()
    string(LENGTH "${token}" length)
    string(SUBSTRING "${input}" ${length} -1 rest)
    set(${token_output} "${token}" PARENT_SCOPE)
    set(${rest_output} "${rest}" PARENT_SCOPE)
endfunction()

function(symphony_receipt_v2_json_value input depth output)
    if(depth GREATER 8)
        message(FATAL_ERROR "receipt-v2 JSON exceeds its nesting bound")
    endif()
    string(REGEX REPLACE "^[ \t\r\n]+" "" rest "${input}")
    string(SUBSTRING "${rest}" 0 1 first)
    if(first STREQUAL "{" OR first STREQUAL "[")
        if(first STREQUAL "{")
            set(closing "}")
            set(object TRUE)
        else()
            set(closing "]")
            set(object FALSE)
        endif()
        string(SUBSTRING "${rest}" 1 -1 rest)
        string(REGEX REPLACE "^[ \t\r\n]+" "" rest "${rest}")
        string(SUBSTRING "${rest}" 0 1 next)
        if(next STREQUAL closing)
            string(SUBSTRING "${rest}" 1 -1 rest)
        else()
            set(seen "")
            math(EXPR next_depth "${depth} + 1")
            set(done FALSE)
            foreach(index RANGE 1 4096)
                if(object)
                    symphony_receipt_v2_json_string_token("${rest}" key_token rest)
                    string(JSON key GET "[${key_token}]" 0)
                    if(NOT key MATCHES "^[a-z_]+$")
                        message(FATAL_ERROR "receipt-v2 JSON contains an invalid member")
                    endif()
                    list(FIND seen "${key}" duplicate)
                    if(NOT duplicate EQUAL -1)
                        message(FATAL_ERROR "receipt-v2 JSON contains a duplicate member: ${key}")
                    endif()
                    list(APPEND seen "${key}")
                    string(REGEX REPLACE "^[ \t\r\n]+" "" rest "${rest}")
                    string(SUBSTRING "${rest}" 0 1 next)
                    if(NOT next STREQUAL ":")
                        message(FATAL_ERROR "receipt-v2 JSON object member lacks a colon")
                    endif()
                    string(SUBSTRING "${rest}" 1 -1 rest)
                endif()
                symphony_receipt_v2_json_value("${rest}" ${next_depth} rest)
                string(REGEX REPLACE "^[ \t\r\n]+" "" rest "${rest}")
                string(SUBSTRING "${rest}" 0 1 next)
                if(next STREQUAL closing)
                    string(SUBSTRING "${rest}" 1 -1 rest)
                    set(done TRUE)
                    break()
                elseif(next STREQUAL ",")
                    string(SUBSTRING "${rest}" 1 -1 rest)
                    string(REGEX REPLACE "^[ \t\r\n]+" "" rest "${rest}")
                else()
                    message(FATAL_ERROR "receipt-v2 JSON collection lacks a delimiter")
                endif()
            endforeach()
            if(NOT done)
                message(FATAL_ERROR "receipt-v2 JSON collection exceeds its bound")
            endif()
        endif()
    elseif(first STREQUAL "\"")
        symphony_receipt_v2_json_string_token("${rest}" token rest)
    else()
        string(REGEX MATCH "^(true|false|null|-?(0|[1-9][0-9]*)(\\.[0-9]+)?([eE][-+]?[0-9]+)?)" token "${rest}")
        if(token STREQUAL "")
            message(FATAL_ERROR "receipt-v2 contains an invalid JSON value")
        endif()
        string(LENGTH "${token}" length)
        string(SUBSTRING "${rest}" ${length} -1 rest)
    endif()
    set(${output} "${rest}" PARENT_SCOPE)
endfunction()

function(symphony_receipt_v2_strict_json input)
    # Reject raw control bytes before token matching, including embedded NUL.
    # Only JSON's whitespace bytes (TAB, LF, CR) may occur outside a string.
    string(HEX "${input}" hex)
    string(REGEX MATCHALL ".." bytes "${hex}")
    foreach(control 00 01 02 03 04 05 06 07 08 0b 0c 0e 0f
        10 11 12 13 14 15 16 17 18 19 1a 1b 1c 1d 1e 1f)
        list(FIND bytes "${control}" position)
        if(NOT position EQUAL -1)
            message(FATAL_ERROR "receipt-v2 JSON contains a raw control byte")
        endif()
    endforeach()
    symphony_receipt_v2_json_value("${input}" 0 rest)
    string(REGEX REPLACE "^[ \t\r\n]+" "" rest "${rest}")
    if(NOT rest STREQUAL "")
        message(FATAL_ERROR "receipt-v2 JSON has trailing bytes")
    endif()
endfunction()

# Receipt-v2 contains only bounded objects, arrays, strings, booleans, nulls,
# and nonnegative integral numbers. Object members are sorted; arrays retain
# their exact order. The caller removes receipt_digest before canonicalization.
function(symphony_receipt_v2_canonical value type depth output)
    if(depth GREATER 8)
        message(FATAL_ERROR "receipt-v2 JSON exceeds its nesting bound")
    endif()
    math(EXPR next_depth "${depth} + 1")
    if(type STREQUAL "OBJECT" OR type STREQUAL "ARRAY")
        string(JSON count LENGTH "${value}")
        if(count GREATER 4096)
            message(FATAL_ERROR "receipt-v2 JSON collection exceeds its bound")
        endif()
        if(type STREQUAL "OBJECT")
            set(result "{")
            set(members "")
            if(count GREATER 0)
                math(EXPR last "${count} - 1")
                foreach(index RANGE 0 ${last})
                    string(JSON member MEMBER "${value}" ${index})
                    if(NOT member MATCHES "^[a-z_]+$")
                        message(FATAL_ERROR "receipt-v2 JSON contains an invalid member")
                    endif()
                    list(APPEND members "${member}")
                endforeach()
                list(SORT members)
            endif()
        else()
            set(result "[")
            set(members "")
            if(count GREATER 0)
                math(EXPR last "${count} - 1")
                foreach(index RANGE 0 ${last})
                    list(APPEND members "${index}")
                endforeach()
            endif()
        endif()
        set(separator "")
        foreach(member IN LISTS members)
            string(JSON child_type TYPE "${value}" "${member}")
            string(JSON child GET "${value}" "${member}")
            symphony_receipt_v2_canonical("${child}" "${child_type}" ${next_depth} encoded)
            string(APPEND result "${separator}")
            if(type STREQUAL "OBJECT")
                string(APPEND result "\"${member}\":")
            endif()
            string(APPEND result "${encoded}")
            set(separator ",")
        endforeach()
        if(type STREQUAL "OBJECT")
            string(APPEND result "}")
        else()
            string(APPEND result "]")
        endif()
    elseif(type STREQUAL "STRING")
        symphony_receipt_v2_json_string("${value}" result)
    elseif(type STREQUAL "NUMBER")
        if(NOT value MATCHES "^(0|[1-9][0-9]*)$" OR value GREATER 9007199254740991)
            message(FATAL_ERROR "receipt-v2 JSON number is not a portable unsigned integer")
        endif()
        set(result "${value}")
    elseif(type STREQUAL "BOOLEAN")
        if(value)
            set(result true)
        else()
            set(result false)
        endif()
    elseif(type STREQUAL "NULL")
        set(result null)
    else()
        message(FATAL_ERROR "receipt-v2 JSON type is unsupported")
    endif()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()
