include_guard(GLOBAL)
get_filename_component(_snv_repo "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
include("${_snv_repo}/cmake/SymphonyInstallReceiptV2.cmake")
include(GNUInstallDirs)
include(CMakePackageConfigHelpers)
include(CTest)

function(symphony_snv_verify_sdk target component release)
  get_target_property(imported ${target} IMPORTED)
  if(NOT imported)
    message(FATAL_ERROR "installed SDK target required: ${target}")
  endif()
  get_target_property(configs ${target} IMPORTED_CONFIGURATIONS)
  if(NOT configs)
    message(FATAL_ERROR "installed SDK has no exported archive configuration: ${target}")
  endif()
  list(GET configs 0 config)
  get_target_property(archive ${target} IMPORTED_LOCATION_${config})
  set(sdk_component "${component}")
  if(component STREQUAL "knowledge-vector-engine-cpp")
    set(sdk_component knowledge-vector-engine)
  endif()
  if(NOT IS_ABSOLUTE "${archive}" OR NOT archive MATCHES "^(.+)/symphony/${sdk_component}/${release}/[^/]+$")
    message(FATAL_ERROR "SDK archive has no exact versioned prefix: ${target}")
  endif()
  set(ancestor "${CMAKE_MATCH_1}")
  set(path "share/symphony/receipts/${component}/${release}/install-receipt.json")
  # GNUInstallDirs permits architecture-qualified and caller-selected library
  # directories. Locate the nearest exact receipt ancestor instead of assuming
  # lib or lib64; all consumed exports must subsequently be owned beneath it.
  set(prefix "")
  foreach(depth RANGE 0 63)
    if(EXISTS "${ancestor}/${path}" OR IS_SYMLINK "${ancestor}/${path}")
      set(prefix "${ancestor}")
      break()
    endif()
    get_filename_component(parent "${ancestor}" DIRECTORY)
    if(parent STREQUAL ancestor)
      break()
    endif()
    set(ancestor "${parent}")
  endforeach()
  if(NOT prefix)
    message(FATAL_ERROR "SDK archive has no exact receipt-bound prefix: ${target}")
  endif()
  symphony_receipt_v2_root("${prefix}" prefix)
  symphony_receipt_v2_no_follow("${prefix}" "${path}")
  symphony_receipt_v2_regular_file("${prefix}/${path}")
  file(READ "${prefix}/${path}" raw LIMIT 262145)
  string(LENGTH "${raw}" size)
  if(size GREATER 262144)
    message(FATAL_ERROR "SDK receipt exceeds bounds")
  endif()
  symphony_receipt_v2_strict_json("${raw}")
  string(JSON protocol GET "${raw}" protocol)
  string(JSON format_version GET "${raw}" format_version)
  string(JSON actual_component GET "${raw}" component_id)
  string(JSON actual_module GET "${raw}" module_id)
  string(JSON actual_package GET "${raw}" package_id)
  string(JSON actual_kind GET "${raw}" component_kind)
  string(JSON actual_release GET "${raw}" version)
  string(JSON expected_digest GET "${raw}" receipt_digest)
  string(JSON unsigned REMOVE "${raw}" receipt_digest)
  symphony_receipt_v2_canonical("${unsigned}" OBJECT 0 canonical)
  string(SHA256 hash "${canonical}")
  if(NOT protocol STREQUAL "symphony.knowledge.install-receipt.v2" OR NOT format_version EQUAL 2 OR
     NOT actual_component STREQUAL component OR NOT actual_module STREQUAL component OR
     NOT actual_package STREQUAL component OR NOT actual_release STREQUAL release OR
     NOT expected_digest STREQUAL "sha256:${hash}")
    message(FATAL_ERROR "exact SDK receipt identity/digest rejected: ${target}")
  endif()
  if(component MATCHES "^(sniv|snrv|sciv|scnv|snv)-engine$")
    set(owner "${CMAKE_MATCH_1}")
    string(JSON actual_vector GET "${raw}" vector_id)
    string(JSON actual_engine GET "${raw}" engine_id)
    if(NOT actual_kind STREQUAL "vector_engine" OR NOT actual_vector STREQUAL owner OR
       NOT actual_engine STREQUAL "symphony-${owner}")
      message(FATAL_ERROR "exact semantic SDK receipt identity rejected: ${target}")
    endif()
  elseif(component STREQUAL "snv-local-observer")
    string(JSON vector_type TYPE "${raw}" vector_id)
    string(JSON engine_type TYPE "${raw}" engine_id)
    string(JSON entries LENGTH "${raw}" entry_points)
    if(NOT actual_kind STREQUAL "module" OR NOT vector_type STREQUAL "NULL" OR
       NOT engine_type STREQUAL "NULL" OR NOT entries EQUAL 1)
      message(FATAL_ERROR "observer SDK must retain its exact finite module identity: ${target}")
    endif()
    string(JSON entry_fields LENGTH "${raw}" entry_points 0)
    string(JSON entry_id GET "${raw}" entry_points 0 entry_point_id)
    string(JSON entry_kind GET "${raw}" entry_points 0 kind)
    string(JSON entry_path GET "${raw}" entry_points 0 path)
    string(JSON entry_protocols LENGTH "${raw}" entry_points 0 protocols)
    string(JSON entry_protocol GET "${raw}" entry_points 0 protocols 0)
    set(expected_entry_path "libexec/symphony/snv-local-observer/${release}/symphony-snv-local-observer")
    if(NOT entry_fields EQUAL 4 OR NOT entry_id STREQUAL "symphony-snv-local-observer" OR
       NOT entry_kind STREQUAL "executable" OR NOT entry_path STREQUAL expected_entry_path OR
       NOT entry_protocols EQUAL 1 OR NOT entry_protocol STREQUAL "symphony.knowledge.engine-process.v1")
      message(FATAL_ERROR "observer SDK finite process entry point rejected: ${target}")
    endif()
  else()
    string(JSON vector_type TYPE "${raw}" vector_id)
    string(JSON engine_type TYPE "${raw}" engine_id)
    string(JSON entries LENGTH "${raw}" entry_points)
    if(NOT actual_kind STREQUAL "module" OR NOT vector_type STREQUAL "NULL" OR
       NOT engine_type STREQUAL "NULL" OR NOT entries EQUAL 0)
      message(FATAL_ERROR "neutral SDK must not claim an engine identity: ${target}")
    endif()
  endif()
  string(JSON count LENGTH "${raw}" files)
  if(count GREATER 512 OR count LESS 1)
    message(FATAL_ERROR "SDK receipt ownership bound rejected")
  endif()
  math(EXPR last "${count}-1")
  set(archive_owned FALSE)
  set(owned_paths "")
  foreach(i RANGE ${last})
    string(JSON owned GET "${raw}" files ${i} path)
    if(owned IN_LIST owned_paths)
      message(FATAL_ERROR "SDK receipt repeats an owned path: ${owned}")
    endif()
    list(APPEND owned_paths "${owned}")
    string(JSON expected GET "${raw}" files ${i} digest)
    string(JSON expected_size GET "${raw}" files ${i} size)
    if(expected_size LESS 0 OR expected_size GREATER 67108864)
      message(FATAL_ERROR "SDK artifact exceeds the independent 64 MiB package bound")
    endif()
    symphony_receipt_v2_no_follow("${prefix}" "${owned}")
    symphony_receipt_v2_regular_file("${prefix}/${owned}")
    file(SHA256 "${prefix}/${owned}" hash)
    file(SIZE "${prefix}/${owned}" size)
    if(NOT expected STREQUAL "sha256:${hash}" OR NOT size EQUAL expected_size)
      message(FATAL_ERROR "SDK receipt-owned bytes changed: ${owned}")
    endif()
    if("${prefix}/${owned}" STREQUAL archive)
      set(archive_owned TRUE)
    endif()
    if(component STREQUAL "snv-local-observer" AND owned STREQUAL expected_entry_path)
      string(JSON owned_kind GET "${raw}" files ${i} kind)
      if(NOT owned_kind STREQUAL "executable")
        message(FATAL_ERROR "observer SDK finite process ownership kind rejected: ${target}")
      endif()
    endif()
  endforeach()
  if(NOT archive_owned)
    message(FATAL_ERROR "SDK archive is not bound by its exact receipt")
  endif()
  if(component STREQUAL "snv-local-observer" AND NOT expected_entry_path IN_LIST owned_paths)
    message(FATAL_ERROR "observer SDK finite process is not receipt-owned: ${target}")
  endif()

  # Archive correspondence alone is insufficient: these exported directories
  # are consumed by the compiler, and these CMake files select its SDK target.
  # Receipts are byte/ownership evidence, not publisher authentication; package
  # configuration is already executable CMake when find_package returns.
  get_target_property(include_dirs ${target} INTERFACE_INCLUDE_DIRECTORIES)
  if(NOT include_dirs)
    message(FATAL_ERROR "installed SDK has no exported public include directory: ${target}")
  endif()
  list(REMOVE_DUPLICATES include_dirs)
  foreach(include_dir IN LISTS include_dirs)
    file(RELATIVE_PATH relative "${prefix}" "${include_dir}")
    symphony_receipt_v2_no_follow("${prefix}" "${relative}")
    if(NOT IS_DIRECTORY "${include_dir}" OR NOT relative MATCHES "(^|/)symphony/${sdk_component}/${release}$")
      message(FATAL_ERROR "SDK public includes have no exact component/version scope: ${target}")
    endif()
    file(GLOB_RECURSE exports LIST_DIRECTORIES true RELATIVE "${prefix}" "${include_dir}/*")
    list(LENGTH exports export_count)
    if(export_count LESS 1 OR export_count GREATER 512)
      message(FATAL_ERROR "SDK public include ownership bound rejected: ${target}")
    endif()
    foreach(export IN LISTS exports)
      symphony_receipt_v2_no_follow("${prefix}" "${export}")
      if(NOT IS_DIRECTORY "${prefix}/${export}" AND NOT export IN_LIST owned_paths)
        message(FATAL_ERROR "SDK exported public file is not receipt-owned: ${export}")
      endif()
    endforeach()
  endforeach()
  string(REPLACE "Symphony::" "Symphony" package "${target}")
  set(package_dir "${${package}_DIR}")
  if(NOT package_dir)
    message(FATAL_ERROR "SDK exact package configuration directory unavailable: ${target}")
  endif()
  file(RELATIVE_PATH relative "${prefix}" "${package_dir}")
  symphony_receipt_v2_no_follow("${prefix}" "${relative}")
  if(NOT relative MATCHES "(^|/)cmake/${package}-${release}$")
    message(FATAL_ERROR "SDK configuration has no exact package/version scope: ${target}")
  endif()
  set(config_files "${package}Config.cmake" "${package}ConfigVersion.cmake" "${package}Targets.cmake")
  foreach(config IN LISTS configs)
    string(TOLOWER "${config}" lower_config)
    list(APPEND config_files "${package}Targets-${lower_config}.cmake")
    get_target_property(config_archive ${target} IMPORTED_LOCATION_${config})
    file(RELATIVE_PATH config_archive_relative "${prefix}" "${config_archive}")
    if(NOT config_archive_relative IN_LIST owned_paths)
      message(FATAL_ERROR "SDK configured archive is not receipt-owned: ${target}/${config}")
    endif()
  endforeach()
  foreach(config_file IN LISTS config_files)
    if(NOT "${relative}/${config_file}" IN_LIST owned_paths)
      message(FATAL_ERROR "SDK exported CMake file is not receipt-owned: ${relative}/${config_file}")
    endif()
  endforeach()
endfunction()

function(symphony_snv_engine)
  cmake_parse_arguments(P "MECHANICS" "OWNER;SDK" "SOURCES;TEST_SOURCES;EXTRA_LIBRARIES;DEPENDENCIES" ${ARGN})
  if(NOT P_OWNER OR NOT P_SDK OR NOT P_SOURCES)
    message(FATAL_ERROR "SNV OWNER SDK SOURCES required")
  endif()
  if(CMAKE_CONFIGURATION_TYPES)
    message(FATAL_ERROR "SNV receipt requires single-configuration generator")
  endif()
  if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Release CACHE STRING "Build type" FORCE)
  endif()
  option(SYMPHONY_SNV_USE_INSTALLED_DEPENDENCIES "Use exact installed SDKs" OFF)
  if(SYMPHONY_SNV_USE_INSTALLED_DEPENDENCIES)
    find_package(SymphonyKnowledgeVectorEngine 0.2.0 EXACT REQUIRED CONFIG)
    symphony_snv_verify_sdk(Symphony::KnowledgeVectorEngine knowledge-vector-engine-cpp 0.2.0-dev)
    if(NOT P_MECHANICS)
      find_package(SymphonySnvCommon 0.1.0 EXACT REQUIRED CONFIG)
      symphony_snv_verify_sdk(Symphony::SnvCommon snv-common-cpp 0.1.0-dev)
    endif()
  else()
    if(NOT TARGET Symphony::KnowledgeVectorEngine)
      set(SYMPHONY_KVE_BUILD_TESTING OFF CACHE BOOL "" FORCE)
      add_subdirectory("${_snv_repo}/libraries/knowledge-vector-engine-cpp" "${CMAKE_BINARY_DIR}/foundation")
    endif()
    if(NOT P_MECHANICS AND NOT TARGET Symphony::SnvCommon)
      add_subdirectory("${_snv_repo}/libraries/snv-common-cpp" "${CMAKE_BINARY_DIR}/common")
    endif()
  endif()
  set(package "Symphony${P_SDK}")
  set(target "symphony-${P_OWNER}")
  set(release "0.1.0-dev")
  set(component "${P_OWNER}-engine")
  if(P_MECHANICS)
    set(component "snv-common-cpp")
  endif()
  set(inc "${CMAKE_INSTALL_INCLUDEDIR}/symphony/${component}/${release}")
  set(lib "${CMAKE_INSTALL_LIBDIR}/symphony/${component}/${release}")
  set(config "${CMAKE_INSTALL_LIBDIR}/cmake/${package}-${release}")
  set(share "share/symphony/${component}/${release}")
  set(receipt "share/symphony/receipts/${component}/${release}/install-receipt.json")
  symphony_install_receipt_v2_preflight(RECEIPT_PATH "${receipt}")
  add_library(${target} STATIC ${P_SOURCES})
  add_library(Symphony::${P_SDK} ALIAS ${target})
  set_target_properties(${target} PROPERTIES CXX_STANDARD 26 CXX_STANDARD_REQUIRED ON CXX_EXTENSIONS OFF EXPORT_NAME ${P_SDK})
  target_compile_features(${target} PUBLIC cxx_std_26)
  target_compile_options(${target} PRIVATE $<$<CXX_COMPILER_ID:AppleClang,Clang,GNU>:-Wall;-Wextra;-Wpedantic;-Werror>)
  target_include_directories(${target} PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include> $<INSTALL_INTERFACE:${inc}>)
  target_link_libraries(${target} PUBLIC Symphony::KnowledgeVectorEngine ${P_EXTRA_LIBRARIES})
  if(NOT P_MECHANICS)
    target_link_libraries(${target} PUBLIC Symphony::SnvCommon)
    add_executable(${component} "${_snv_repo}/cmake/SymphonySnvMain.cpp")
    set_target_properties(${component} PROPERTIES CXX_STANDARD 26 CXX_STANDARD_REQUIRED ON CXX_EXTENSIONS OFF OUTPUT_NAME symphony-${P_OWNER})
    target_compile_definitions(${component} PRIVATE SNV_HEADER="symphony/snv/${P_OWNER}.hpp" SNV_OWNER=${P_OWNER} SNV_OWNER_TEXT="${P_OWNER}")
    target_link_libraries(${component} PRIVATE ${target})
    if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/src/interface.generated.hpp")
      target_include_directories(${component} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src")
      target_compile_definitions(${component} PRIVATE SNV_GENERATED_INTERFACE=1)
    endif()
    install(TARGETS ${component} RUNTIME DESTINATION "libexec/symphony/${component}/${release}")
    set(owned "libexec/symphony/${component}/${release}/symphony-${P_OWNER}|executable")
    set(entries "symphony-${P_OWNER}|executable|libexec/symphony/${component}/${release}/symphony-${P_OWNER}|symphony.knowledge.engine-process.v1")
  endif()
  install(TARGETS ${target} EXPORT ${package}Targets ARCHIVE DESTINATION "${lib}")
  install(DIRECTORY include/ DESTINATION "${inc}")
  file(GLOB_RECURSE headers RELATIVE "${CMAKE_CURRENT_SOURCE_DIR}/include" "${CMAKE_CURRENT_SOURCE_DIR}/include/*.hpp")
  foreach(h IN LISTS headers)
    list(APPEND owned "${inc}/${h}|regular")
  endforeach()
  string(TOLOWER "${CMAKE_BUILD_TYPE}" build_type)
  list(APPEND owned "${lib}/${CMAKE_STATIC_LIBRARY_PREFIX}${target}${CMAKE_STATIC_LIBRARY_SUFFIX}|regular")
  set(config_text "include(CMakeFindDependencyMacro)\nfind_dependency(SymphonyKnowledgeVectorEngine 0.2.0 EXACT CONFIG)\n")
  if(NOT P_MECHANICS)
    string(APPEND config_text "find_dependency(SymphonySnvCommon 0.1.0 EXACT CONFIG)\n")
  endif()
  foreach(dep IN LISTS P_DEPENDENCIES)
    string(APPEND config_text "find_dependency(${dep} 0.1.0 EXACT CONFIG)\n")
  endforeach()
  string(APPEND config_text "include(\"\${CMAKE_CURRENT_LIST_DIR}/${package}Targets.cmake\")\n")
  file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/${package}Config.cmake" "${config_text}")
  write_basic_package_version_file("${CMAKE_CURRENT_BINARY_DIR}/${package}ConfigVersion.cmake" VERSION 0.1.0 COMPATIBILITY ExactVersion)
  install(EXPORT ${package}Targets FILE ${package}Targets.cmake NAMESPACE Symphony:: DESTINATION "${config}")
  install(FILES "${CMAKE_CURRENT_BINARY_DIR}/${package}Config.cmake" "${CMAKE_CURRENT_BINARY_DIR}/${package}ConfigVersion.cmake" DESTINATION "${config}")
  foreach(f Config.cmake ConfigVersion.cmake Targets.cmake Targets-${build_type}.cmake)
    list(APPEND owned "${config}/${package}${f}|regular")
  endforeach()
  foreach(doc INTENT.md MANIFEST.md INSTALL.md SKILL.md SPEC.md FEATURES.md)
    install(FILES "${doc}" DESTINATION "share/doc/symphony/${component}/${release}")
    list(APPEND owned "share/doc/symphony/${component}/${release}/${doc}|regular")
  endforeach()
  foreach(meta OWNER-INTERFACE.json INTERFACE-GENERATOR.json)
    if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${meta}")
      install(FILES "${meta}" DESTINATION "${share}")
      list(APPEND owned "${share}/${meta}|regular")
    endif()
  endforeach()
  file(GLOB_RECURSE resources RELATIVE "${CMAKE_CURRENT_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}/schemas/*.json")
  foreach(f IN LISTS resources)
    install(FILES "${f}" DESTINATION "${share}/schemas/v1")
    get_filename_component(fname "${f}" NAME)
    list(APPEND owned "${share}/schemas/v1/${fname}|regular")
  endforeach()
  install(FILES "${_snv_repo}/LICENSE" DESTINATION "share/licenses/symphony-${component}/${release}" RENAME LICENSE-AGPL-3.0)
  list(APPEND owned "share/licenses/symphony-${component}/${release}/LICENSE-AGPL-3.0|regular")
  install(FILES "${_snv_repo}/libraries/knowledge-vector-engine-cpp/third_party/nlohmann/LICENSE.MIT"
    DESTINATION "share/licenses/symphony-${component}/${release}" RENAME nlohmann-json-LICENSE.MIT)
  list(APPEND owned "share/licenses/symphony-${component}/${release}/nlohmann-json-LICENSE.MIT|regular")
  if(P_MECHANICS)
    symphony_install_receipt_v2(COMPONENT_ID "${component}" COMPONENT_KIND module MODULE_ID "${component}"
      PACKAGE_ID "${component}" VERSION "${release}" RECEIPT_PATH "${receipt}" OWNED_FILES ${owned})
  else()
    symphony_install_receipt_v2(COMPONENT_ID "${component}" COMPONENT_KIND vector_engine MODULE_ID "${component}"
      VECTOR_ID "${P_OWNER}" ENGINE_ID "symphony-${P_OWNER}" PACKAGE_ID "${component}" VERSION "${release}"
      RECEIPT_PATH "${receipt}" OWNED_FILES ${owned} ENTRY_POINTS ${entries})
  endif()
  set(uninstall_files "")
  foreach(spec IN LISTS owned)
    string(REPLACE "|" ";" fields "${spec}")
    list(GET fields 0 path)
    string(APPEND uninstall_files " [==[${path}]==]")
  endforeach()
  file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/uninstall.cmake" "if(NOT DEFINED INSTALL_PREFIX)\nset(INSTALL_PREFIX [==[${CMAKE_INSTALL_PREFIX}]==])\nendif()\nset(_files${uninstall_files} [==[${receipt}]==])\ninclude(\"\${CMAKE_CURRENT_LIST_DIR}/SymphonyUninstallReceiptV2.cmake\")\n")
  add_custom_target(uninstall-${component} COMMAND ${CMAKE_COMMAND} -DINSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} -P "${CMAKE_CURRENT_BINARY_DIR}/uninstall.cmake")
  if(BUILD_TESTING AND P_TEST_SOURCES)
    add_executable(${component}-tests ${P_TEST_SOURCES})
    target_link_libraries(${component}-tests PRIVATE ${target})
    set_target_properties(${component}-tests PROPERTIES CXX_STANDARD 26 CXX_STANDARD_REQUIRED ON CXX_EXTENSIONS OFF)
    target_compile_options(${component}-tests PRIVATE $<$<CXX_COMPILER_ID:AppleClang,Clang,GNU>:-Wall;-Wextra;-Wpedantic;-Werror>)
    add_test(NAME ${component}-tests COMMAND ${component}-tests)
    if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/tests/process.cpp")
      add_executable(${component}-process-tests tests/process.cpp)
      target_link_libraries(${component}-process-tests PRIVATE ${target})
      target_include_directories(${component}-process-tests PRIVATE "${_snv_repo}/libraries/knowledge-vector-engine-cpp/tests/support" "${_snv_repo}/tests/snv")
      set_target_properties(${component}-process-tests PROPERTIES CXX_STANDARD 26 CXX_STANDARD_REQUIRED ON CXX_EXTENSIONS OFF)
      target_compile_options(${component}-process-tests PRIVATE $<$<CXX_COMPILER_ID:AppleClang,Clang,GNU>:-Wall;-Wextra;-Wpedantic;-Werror>)
    endif()
  endif()
endfunction()
