include(CTest)
include(GNUInstallDirs)
include("${SYMPHONY_REPOSITORY_ROOT}/cmake/SymphonyInstallReceiptV2.cmake")
function(symphony_sqv_administration module vector kind)
  if(NOT CMAKE_INSTALL_LIBEXECDIR STREQUAL "libexec" OR NOT CMAKE_INSTALL_DATADIR STREQUAL "share")
    message(FATAL_ERROR "SQV administration receipt requires exact libexec/share layout")
  endif()
  option(SYMPHONY_SQV_ADMIN_INSTALLED "Build against exact installed native libraries" OFF)
  if(SYMPHONY_SQV_ADMIN_INSTALLED)
    find_package(SymphonyKnowledgeVectorEngine 0.2.0 EXACT REQUIRED CONFIG)
    find_package(SymphonySqfvBatch 0.3.0 EXACT REQUIRED CONFIG)
    find_package(SymphonySqmvMetadata 0.2.0 EXACT REQUIRED CONFIG)
    if(vector STREQUAL "sqtv")
      find_package(SymphonySqtvIntegerConversion 0.2.0 EXACT REQUIRED CONFIG)
    endif()
  else()
    function(dependencies)
      set(BUILD_TESTING OFF)
      if(NOT TARGET Symphony::SqmvMetadata)
        add_subdirectory("${SYMPHONY_REPOSITORY_ROOT}/modules/sqmv-metadata-cpp" "${CMAKE_CURRENT_BINARY_DIR}/metadata" EXCLUDE_FROM_ALL)
      endif()
      if(NOT TARGET Symphony::SqtvIntegerConversion AND "${vector}" STREQUAL "sqtv")
        add_subdirectory("${SYMPHONY_REPOSITORY_ROOT}/modules/sqtv-integer-conversion-cpp" "${CMAKE_CURRENT_BINARY_DIR}/conversion" EXCLUDE_FROM_ALL)
      endif()
    endfunction()
    dependencies()
    foreach(binding "sqmv-metadata-cpp|SymphonySqmvMetadata|0.2.0" "sqfv-batch-cpp|SymphonySqfvBatch|0.3.0")
      string(REPLACE "|" ";" parts "${binding}")
      list(GET parts 0 dependency)
      list(GET parts 1 project_name)
      list(GET parts 2 required_version)
      get_directory_property(source_version DIRECTORY "${SYMPHONY_REPOSITORY_ROOT}/modules/${dependency}" DEFINITION ${project_name}_VERSION)
      if(NOT source_version STREQUAL required_version)
        message(FATAL_ERROR "${module} requires ${dependency} ${required_version}")
      endif()
    endforeach()
    get_directory_property(foundation_version DIRECTORY "${SYMPHONY_REPOSITORY_ROOT}/libraries/knowledge-vector-engine-cpp" DEFINITION SymphonyKnowledgeVectorEngine_VERSION)
    if(NOT foundation_version STREQUAL "0.2.0")
      message(FATAL_ERROR "SQV administration requires KnowledgeVectorEngine 0.2.0")
    endif()
  endif()
  set(support "${SYMPHONY_REPOSITORY_ROOT}/tools/sqv-administration-cpp")
  set(engine "symphony-${vector}-${kind}")
  add_library(${module}-core STATIC src/admin.cpp "${support}/request.cpp")
  target_include_directories(${module}-core PUBLIC src "${support}")
  target_compile_definitions(${module}-core PUBLIC SQV_NAMESPACE=symphony::${vector}::administration SQV_ENGINE="${engine}" SQV_MODULE="${module}" SQV_VECTOR="${vector}")
  target_link_libraries(${module}-core PUBLIC Symphony::SqmvMetadata Symphony::KnowledgeVectorEngine)
  if(vector STREQUAL "sqtv")
    if(NOT SYMPHONY_SQV_ADMIN_INSTALLED)
      get_directory_property(conversion_version DIRECTORY "${SYMPHONY_REPOSITORY_ROOT}/modules/sqtv-integer-conversion-cpp" DEFINITION SymphonySqtvIntegerConversion_VERSION)
      if(NOT conversion_version STREQUAL "0.2.0")
        message(FATAL_ERROR "SQTV administration requires conversion 0.2.0")
      endif()
    endif()
    target_link_libraries(${module}-core PUBLIC Symphony::SqtvIntegerConversion)
  endif()
  if(vector STREQUAL "sqpv" OR vector STREQUAL "sqdv" OR vector STREQUAL "sqav")
    target_sources(${module}-core PRIVATE "${SYMPHONY_REPOSITORY_ROOT}/modules/sqpv-inspection-engine/src/store_reader.cpp")
    target_include_directories(${module}-core PUBLIC "${SYMPHONY_REPOSITORY_ROOT}/modules/sqpv-inspection-engine/src")
  endif()
  add_executable(${engine} "${support}/main.cpp")
  target_link_libraries(${engine} PRIVATE ${module}-core)
  foreach(target ${module}-core ${engine})
    set_target_properties(${target} PROPERTIES CXX_STANDARD 26 CXX_STANDARD_REQUIRED ON CXX_EXTENSIONS OFF)
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Werror)
  endforeach()
  if(BUILD_TESTING)
    include("${SYMPHONY_REPOSITORY_ROOT}/cmake/SymphonyNativeTests.cmake")
    symphony_native_test(${module}-process-test "${CMAKE_CURRENT_SOURCE_DIR}/tests/process.cpp")
  endif()
  set(RELEASE "${PROJECT_VERSION}-dev")
  set(RUNTIME "libexec/symphony/${module}/${RELEASE}")
  set(DOCS "share/doc/symphony/${module}/${RELEASE}")
  set(SCHEMAS "share/symphony/schemas/${module}/${RELEASE}")
  set(LICENSES "share/licenses/symphony-${module}/${RELEASE}")
  set(RECEIPT "share/symphony/receipts/${module}/${RELEASE}/install-receipt.json")
  set(OWNED "${RUNTIME}/${engine}|executable")
  set(INSTALLED "${RUNTIME}/${engine}")
  macro(own path)
    list(APPEND OWNED "${path}|regular")
    list(APPEND INSTALLED "${path}")
  endmacro()
  symphony_install_receipt_v2_preflight(RECEIPT_PATH "${RECEIPT}")
  install(TARGETS ${engine} RUNTIME DESTINATION "${RUNTIME}")
  foreach(doc INTENT.md MANIFEST.md SPEC.md SKILL.md INSTALL.md FEATURES.md)
    install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/${doc}" DESTINATION "${DOCS}")
    own("${DOCS}/${doc}")
  endforeach()
  foreach(path IN LISTS ARGN)
    get_filename_component(name "${path}" NAME)
    install(FILES "${path}" DESTINATION "${SCHEMAS}")
    own("${SCHEMAS}/${name}")
  endforeach()
  set(INTERFACE_DIR "share/symphony/contracts/${module}/${RELEASE}")
  install(FILES OWNER-INTERFACE.json DESTINATION "${INTERFACE_DIR}")
  own("${INTERFACE_DIR}/OWNER-INTERFACE.json")
  install(FILES "${SYMPHONY_REPOSITORY_ROOT}/LICENSE" DESTINATION "${LICENSES}" RENAME LICENSE-AGPL-3.0)
  install(FILES "${SYMPHONY_REPOSITORY_ROOT}/libraries/knowledge-vector-engine-cpp/third_party/nlohmann/LICENSE.MIT" DESTINATION "${LICENSES}" RENAME nlohmann-json-LICENSE.MIT)
  foreach(name LICENSE-AGPL-3.0 nlohmann-json-LICENSE.MIT)
    own("${LICENSES}/${name}")
  endforeach()
  symphony_install_receipt_v2(COMPONENT_ID "${module}" COMPONENT_KIND vector_engine MODULE_ID "${module}" VECTOR_ID "${vector}" ENGINE_ID "${engine}" PACKAGE_ID "${module}" VERSION "${RELEASE}" RECEIPT_PATH "${RECEIPT}" OWNED_FILES ${OWNED} ENTRY_POINTS "${engine}|executable|${RUNTIME}/${engine}|symphony.knowledge.engine-process.v1")
  configure_file(cmake/uninstall.cmake.in "${CMAKE_CURRENT_BINARY_DIR}/uninstall.cmake" @ONLY)
  add_custom_target(uninstall-${module} COMMAND ${CMAKE_COMMAND} -DINSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} -P "${CMAKE_CURRENT_BINARY_DIR}/uninstall.cmake")
endfunction()
