// Generated by owner_codegen.cpp; do not edit.
#pragma once
#include "symphony/knowledge/engine/operation.hpp"
namespace symphony::snv::local_observer::interface {
namespace engine = symphony::knowledge::engine;
inline constexpr auto version = "0.1.0-dev";
inline std::vector<engine::OperationSpec> interface_operations() { return {
  {"engop:symphony:snv-local-observer.observe", "observe", "implemented", false, true, {"ssfv:symphony:snv-local-observer"}, {"inspect"}, "qxctl_required", "symphony.snv.local-observe-input.v1", "symphony.snv.local-observe.v1", "read_only", "non_idempotent", false, "none", "", "supported", "freezing"},
}; }
}
