cmake_minimum_required(VERSION 3.30)
foreach(required PACKAGE_BINARY_DIR PACKAGE_MODULE PACKAGE_CMAKE_NAME)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "package lifecycle test lacks ${required}")
    endif()
endforeach()
set(test_root "${PACKAGE_BINARY_DIR}/package-lifecycle-test")
file(REMOVE_RECURSE "${test_root}")
file(MAKE_DIRECTORY "${test_root}")
set(prefix "${test_root}/prefix")
set(receipt_relative "share/symphony/receipts/${PACKAGE_MODULE}/0.5.0-dev/install-receipt.json")
function(run_expect label expected)
    execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
    if(NOT result MATCHES "^[0-9]+$" OR (expected AND NOT result EQUAL 0) OR (NOT expected AND result EQUAL 0))
        message(FATAL_ERROR "${label}: unexpected result ${result}\n${output}\n${error}")
    endif()
endfunction()
run_expect("fresh isolated install" TRUE "${CMAKE_COMMAND}" --install "${PACKAGE_BINARY_DIR}" --prefix "${prefix}")
file(READ "${prefix}/${receipt_relative}" receipt)
string(JSON count LENGTH "${receipt}" files)
string(JSON module GET "${receipt}" module_id)
string(JSON version GET "${receipt}" version)
string(JSON kind GET "${receipt}" component_kind)
string(JSON engine_type TYPE "${receipt}" engine_id)
string(JSON entry_count LENGTH "${receipt}" entry_points)
if(NOT count EQUAL 16 OR NOT module STREQUAL PACKAGE_MODULE OR
   NOT version STREQUAL "0.5.0-dev" OR NOT kind STREQUAL "module" OR
   NOT engine_type STREQUAL "NULL" OR NOT entry_count EQUAL 0)
    message(FATAL_ERROR "unexpected library-only package receipt")
endif()
file(GLOB_RECURSE receipts "${prefix}/share/symphony/receipts/*/install-receipt.json")
list(LENGTH receipts receipt_count)
if(NOT receipt_count EQUAL 1)
    message(FATAL_ERROR "install unexpectedly included source-build dependencies")
endif()
set(owned "")
math(EXPR last "${count} - 1")
foreach(index RANGE 0 ${last})
    string(JSON relative GET "${receipt}" files ${index} path)
    string(JSON size GET "${receipt}" files ${index} size)
    string(JSON digest GET "${receipt}" files ${index} digest)
    file(SIZE "${prefix}/${relative}" actual_size)
    file(SHA256 "${prefix}/${relative}" actual_digest)
    if(NOT actual_size EQUAL size OR NOT digest STREQUAL "sha256:${actual_digest}")
        message(FATAL_ERROR "owned-file receipt mismatch: ${relative}")
    endif()
    list(APPEND owned "${relative}")
endforeach()
run_expect("same-version overwrite refusal" FALSE
    "${CMAKE_COMMAND}" --install "${PACKAGE_BINARY_DIR}" --prefix "${prefix}")
set(probe "${test_root}/wrong-version")
file(MAKE_DIRECTORY "${probe}")
file(WRITE "${probe}/CMakeLists.txt" "cmake_minimum_required(VERSION 3.30)\nproject(ExactPackageProbe LANGUAGES CXX)\nfind_package(${PACKAGE_CMAKE_NAME} 9.9.9 EXACT REQUIRED CONFIG)\n")
run_expect("wrong exact package version" FALSE "${CMAKE_COMMAND}" -S "${probe}" -B "${probe}/build"
    "-DCMAKE_PREFIX_PATH=${prefix}")
set(detached "${test_root}/detached")
file(MAKE_DIRECTORY "${detached}")
string(MAKE_C_IDENTIFIER "${receipt_relative}" identity_id)
foreach(script uninstall.cmake SymphonyUninstallReceiptV2.cmake SymphonyReceiptV2Support.cmake
    "symphony-receipt-v2-identity-${identity_id}.cmake")
    file(COPY "${PACKAGE_BINARY_DIR}/${script}" DESTINATION "${detached}")
endforeach()
set(spec "${prefix}/share/doc/symphony/${PACKAGE_MODULE}/0.5.0-dev/SPEC.md")
file(COPY_FILE "${spec}" "${test_root}/original-spec")
file(APPEND "${spec}" "\ntamper")
run_expect("altered owned content refusal" FALSE
    "${CMAKE_COMMAND}" "-DINSTALL_PREFIX=${prefix}" -P "${detached}/uninstall.cmake")
foreach(relative IN LISTS owned)
    if(NOT EXISTS "${prefix}/${relative}")
        message(FATAL_ERROR "failed uninstall deleted owned content")
    endif()
endforeach()
file(COPY_FILE "${test_root}/original-spec" "${spec}")
file(WRITE "${prefix}/keep.txt" "unrelated administrator file\n")
run_expect("detached guarded removal" TRUE
    "${CMAKE_COMMAND}" "-DINSTALL_PREFIX=${prefix}" -P "${detached}/uninstall.cmake")
foreach(relative IN LISTS owned)
    if(EXISTS "${prefix}/${relative}")
        message(FATAL_ERROR "uninstall retained an owned file")
    endif()
endforeach()
if(EXISTS "${prefix}/${receipt_relative}" OR NOT EXISTS "${prefix}/keep.txt")
    message(FATAL_ERROR "uninstall violated receipt or unrelated-file ownership")
endif()
run_expect("absent package retry" TRUE
    "${CMAKE_COMMAND}" "-DINSTALL_PREFIX=${prefix}" -P "${detached}/uninstall.cmake")
message(STATUS "${PACKAGE_MODULE}: isolated receipt, exact version, immutable install and detached guarded removal passed")
