// Generated by owner_codegen.cpp; do not edit.
#pragma once
#include "symphony/knowledge/engine/operation.hpp"
namespace symphony::sqav::administration {
namespace engine = symphony::knowledge::engine;
inline constexpr auto version = "0.1.0-dev";
inline std::vector<engine::OperationSpec> interface_operations() { return {
  {"engop:symphony:sqav-attempt.inspect", "attempts_inspect", "implemented", false, true, {"ssfv:symphony:sqav-attempt-engine"}, {"inspect"}, "qxctl_required", "symphony.sqav.attempts-inspect-input.v1", "symphony.sqav.attempts-inspect.v1", "read_only", "idempotent", false, "none", "", "supported", "freezing"},
}; }
}
