#include "../src/combinatorial.hpp"
#include <cstdlib>
#include <filesystem>
#include <iostream>
#include <random>
#include <source_location>
#include <unistd.h>
namespace s = symphony::sbv;
namespace d = s::detail;
namespace c = d::combinatorial;
namespace e = symphony::knowledge::engine;
using J = s::Json;
using U = std::uint64_t;
unsigned checks = 0;
void check(bool b, std::source_location l = std::source_location::current()) {
  ++checks;
  if (!b)
    throw std::runtime_error("combinatorial assertion " +
                             std::to_string(l.line()));
}
int main() try {
  // Independent bit-mask enumeration, sorted as tuples, tests every rank and
  // successor, including first/last groups and k=1/n-1.
  for (unsigned n = 2; n <= 9; ++n) {
    for (unsigned k = 1; k < n; ++k) {
      std::vector<std::vector<std::size_t>> oracle;
      for (unsigned mask = 0; mask < (1U << n); ++mask) {
        std::vector<std::size_t> v;
        for (unsigned i = 0; i < n; ++i)
          if (mask & (1U << i))
            v.push_back(i);
        if (v.size() == k)
          oracle.push_back(v);
      }
      std::sort(oracle.begin(), oracle.end());
      check(c::choose(n, k, e::no_deadline).text() == d::dec(oracle.size()));
      auto successor = oracle.front();
      for (std::size_t rank = 0; rank < oracle.size(); ++rank) {
        check(c::unrank(n, k, c::Natural(rank), e::no_deadline) ==
              oracle[rank]);
        check(successor == oracle[rank]);
        if (rank + 1 < oracle.size())
          c::next(successor, n);
      }
    }
  }
  // Exact constants independently generated by integer binomial arithmetic.
  check(c::choose(100, 50, e::no_deadline).text() ==
        "100891344545564193334812497256");
  const std::string total200 =
      "90548514656103281165404177077484163874504589675413336841320";
  check(c::choose(200, 100, e::no_deadline).text() == total200);
  char tmp[] = "/private/tmp/sbv-combinatorial-XXXXXX";
  const auto *env = std::getenv("SYMPHONY_SBV_COMBINATORIAL_FIXTURES");
  const auto *created = env ? env : mkdtemp(tmp);
  check(created != nullptr);
  std::filesystem::path root(created);
  std::filesystem::create_directories(root);
  unsigned seq = 0;
  auto path = [&](const std::string &x) { return (root / x).string(); };
  auto read = [&](const std::string &x) {
    auto r = e::parse_bounded_json(d::read_file(x, e::no_deadline),
                                   d::artifact_bytes, d::artifact_values);
    s::validate_result(r);
    return r;
  };
  auto source = [&](const J &rows) {
    auto r =
        d::base("mechanical sample intervals, not calibrated market labels");
    r["sections"]["observations"] = d::section(rows);
    r = s::seal_result(r);
    auto name = path("source-" + d::dec(++seq) + ".json");
    d::create_file(name, r.dump(), e::no_deadline);
    return J{{"path", name}, {"expected_sha256", r["content_sha256"]}};
  };
  auto groups = [](unsigned n) {
    J out = J::array();
    for (unsigned i = 0; i < n; ++i)
      out.push_back({{"id", "g" + d::dec(i)},
                     {"start_ns", d::dec(10 + 25 * i)},
                     {"end_ns", d::dec(30 + 25 * i)}});
    return out;
  };
  std::mt19937 rng(39731);
  J rows = J::array();
  for (unsigned i = 0; i < 180; ++i) {
    U a = 5 + rng() % 165, b = a + rng() % 27;
    rows.push_back({{"id", d::dec(i)},
                    {"start_ns", d::dec(a)},
                    {"end_ns", d::dec(b)},
                    {"available_ns", d::dec(b + rng() % 13)},
                    {"value", d::dec(a)},
                    {"private", J::array({true, "\u001b"})}});
  }
  // Shared endpoints, crossed group ends and distinct embargo intervals.
  rows.push_back({{"id", "edge"},
                  {"start_ns", "30"},
                  {"end_ns", "35"},
                  {"available_ns", "35"}});
  auto src = source(rows);
  J p{{"protocol", "symphony.sbv.split-input.v1"},
      {"path", src["path"]},
      {"expected_sha256", src["expected_sha256"]},
      {"output_path", ""},
      {"pointer", "/sections/observations/data"},
      {"id_pointer", "/id"},
      {"start_pointer", "/start_ns"},
      {"end_pointer", "/end_ns"},
      {"available_pointer", "/available_ns"},
      {"clock_domain", "mechanical_ns"},
      {"input_description", "unverified fixture labels"},
      {"plan",
       {{"kind", "combinatorial"},
        {"groups", groups(6)},
        {"test_group_count", "2"},
        {"fold_offset", "0"},
        {"fold_count", nullptr},
        {"fit_cutoff_ns", "120"}}},
      {"chronology", "unrestricted"},
      {"purge", "label_overlap"},
      {"purge_before_ns", "3"},
      {"purge_after_ns", "7"},
      {"embargo_ns", "9"},
      {"availability", "by_fit_cutoff"},
      {"retain_rows", true},
      {"extensions", {{"unknown", J::array({"keep", true})}}}};
  auto call = [&](J q) {
    q["output_path"] = path("result-" + d::dec(++seq) + ".json");
    auto receipt = s::dispatch("split", q, e::no_deadline);
    auto r = read(q["output_path"]);
    check(r["content_sha256"] == receipt["content_sha256"]);
    return r;
  };
  auto reject = [&](J q, std::int64_t end = e::no_deadline) {
    q["output_path"] = path("refused-" + d::dec(++seq) + ".json");
    bool failed = false;
    try {
      s::dispatch("split", q, end);
    } catch (const std::exception &) {
      failed = true;
    }
    check(failed);
    check(!std::filesystem::exists(q["output_path"].get<std::string>()));
  };
  auto full = call(p);
  check(
      full["sections"]["combination_selection"]["data"]["total_combinations"] ==
      "15");
  check(full["sections"]["combination_selection"]["data"]["complete_space"] ==
        true);
  check(full["sections"]["user_extensions"]["data"] == p["extensions"]);
  for (const auto &g : full["sections"]["groups"]["data"]) {
    check(g["selected_test_folds"] == "5");
    check(g["selected_train_candidate_folds"] == "10");
  }
  auto q = p;
  // Brute-force interval oracle uses unsorted raw rows and pairwise
  // comparisons, independently of native merged unions and binary group lookup.
  for (unsigned mode = 0; mode < 4; ++mode) {
    q = p;
    if (mode & 1) {
      q["purge"] = "none";
      q["purge_before_ns"] = "0";
      q["purge_after_ns"] = "0";
    }
    if (mode & 2)
      q["availability"] = "ignore";
    auto got = call(q);
    for (const auto &f : got["sections"]["folds"]["data"]) {
      std::vector<bool> test_group(6);
      for (const auto &g : f["windows"]["test_groups"])
        test_group[d::u64(g)] = true;
      auto groupof = [&](U t) {
        for (unsigned g = 0; g < 6; ++g)
          if (t >= 10 + 25 * g && t < 30 + 25 * g)
            return g;
        return 6U;
      };
      std::vector<U> ends(6);
      std::vector<bool> seen(6);
      J want_test = J::array(), want_train = J::array(),
        want_excluded = J::array();
      for (unsigned i = 0; i < rows.size(); ++i) {
        auto g = groupof(d::u64(rows[i]["start_ns"]));
        if (g < 6 && test_group[g]) {
          want_test.push_back(d::dec(i));
          ends[g] = std::max(ends[g], d::u64(rows[i]["end_ns"]));
          seen[g] = true;
        }
      }
      U candidates = 0, overlap_count = 0, late_count = 0, embargo_count = 0,
        retained_overlap = 0, retained_late = 0;
      for (unsigned i = 0; i < rows.size(); ++i) {
        auto a = d::u64(rows[i]["start_ns"]), b = d::u64(rows[i]["end_ns"]);
        auto g = groupof(a);
        if (g == 6 || test_group[g])
          continue;
        ++candidates;
        bool overlap = false, padded = false, embargoed = false,
             late = d::u64(rows[i]["available_ns"]) > 120;
        for (const auto &j : want_test) {
          const auto &t = rows[d::u64(j)];
          auto lo = d::u64(t["start_ns"]), hi = d::u64(t["end_ns"]);
          overlap |= a <= hi && b >= lo;
          padded |= a <= hi + d::u64(q["purge_after_ns"]) &&
                    b >= lo - d::u64(q["purge_before_ns"]);
        }
        for (unsigned h = 0; h < 6; ++h)
          embargoed |= seen[h] && a > ends[h] && a <= ends[h] + 9;
        overlap_count += overlap;
        late_count += late;
        embargo_count += embargoed;
        J reasons = J::array();
        if (q["purge"] == "label_overlap" && padded)
          reasons.push_back("label_overlap_or_padding");
        if (embargoed)
          reasons.push_back("embargo");
        if (q["availability"] == "by_fit_cutoff" && late)
          reasons.push_back("unavailable_at_fit_cutoff");
        if (reasons.empty()) {
          want_train.push_back(d::dec(i));
          retained_overlap += overlap;
          retained_late += late;
        } else
          want_excluded.push_back(
              {{"source_index", d::dec(i)}, {"reasons", reasons}});
      }
      check(f["train_indices"] == want_train);
      check(f["test_indices"] == want_test);
      check(f["excluded"] == want_excluded);
      check(f["embargo_interval"].is_null());
      check(f["diagnostics"] ==
            J({{"train_candidates", d::dec(candidates)},
               {"overlap_candidates", d::dec(overlap_count)},
               {"late_candidates", d::dec(late_count)},
               {"unknown_availability_candidates", "0"},
               {"embargo_candidates", d::dec(embargo_count)},
               {"retained_overlaps", d::dec(retained_overlap)},
               {"retained_late", d::dec(retained_late)}}));
      for (unsigned i = 0; i < want_train.size(); ++i)
        check(f["train_rows"][i] == rows[d::u64(want_train[i])]);
      for (unsigned i = 0; i < want_test.size(); ++i)
        check(f["test_rows"][i] == rows[d::u64(want_test[i])]);
    }
  }
  // Independently requested pages reproduce the corresponding immutable folds.
  for (unsigned offset = 0; offset < 15; offset += 3) {
    q = p;
    q["plan"]["fold_offset"] = d::dec(offset);
    q["plan"]["fold_count"] = "3";
    auto page = call(q);
    for (unsigned i = 0; i < 3; ++i)
      check(page["sections"]["folds"]["data"][i] ==
            full["sections"]["folds"]["data"][offset + i]);
    check(
        page["sections"]["combination_selection"]["data"]["next_fold_offset"] ==
        (offset == 12 ? J(nullptr) : J(d::dec(offset + 3))));
  }
  q = p;
  q["plan"]["fold_count"] = "0";
  auto empty = call(q);
  check(empty["sections"]["folds"]["data"].empty());
  check(
      empty["sections"]["combination_selection"]["data"]["next_fold_offset"] ==
      "0");
  q["plan"]["fold_offset"] = "15";
  check(call(q)["sections"]["combination_selection"]["data"]["next_fold_offset"]
            .is_null());
  auto empty_source = source(J::array());
  q = p;
  q["path"] = empty_source["path"];
  q["expected_sha256"] = empty_source["expected_sha256"];
  q["plan"]["groups"] = groups(18);
  auto many = call(q);
  check(many["sections"]["folds"]["data"].size() == 153);
  check(many["sections"]["summary"]["data"]["available_folds"] == "0");
  q["plan"]["groups"] = groups(200);
  q["plan"]["test_group_count"] = "100";
  q["plan"]["fold_count"] = "1";
  q["plan"]["fold_offset"] =
      "90548514656103281165404177077484163874504589675413336841319";
  auto huge = call(q);
  check(
      huge["sections"]["combination_selection"]["data"]["total_combinations"] ==
      total200);
  check(huge["sections"]["combination_selection"]["data"]["next_fold_offset"]
            .is_null());
  for (unsigned i = 0; i < 100; ++i)
    check(huge["sections"]["folds"]["data"][0]["windows"]["test_groups"][i] ==
          d::dec(100 + i));
  q = p;
  q["retain_rows"] = false;
  q["available_pointer"] = nullptr;
  q["availability"] = "ignore";
  check(call(q)["sections"]["folds"]["data"][0]["train_rows"].is_null());
  q = p;
  q["plan"]["test_group_count"] = "1";
  q["plan"]["fold_offset"] = "5";
  q["plan"]["fold_count"] = "1";
  q["chronology"] = "past_only";
  q["plan"]["fit_cutoff_ns"] = "135";
  check(call(q)["sections"]["folds"]["data"].size() == 1);
  q["plan"]["fold_offset"] = "0";
  reject(q);
  for (const auto &v : J::array({"00", "-1", "+1", "1.0", 2, nullptr})) {
    q = p;
    q["plan"]["fold_offset"] = v;
    reject(q);
  }
  for (const auto &v : J::array({"0", "6", "7"})) {
    q = p;
    q["plan"]["test_group_count"] = v;
    reject(q);
  }
  q = p;
  q["plan"]["fold_offset"] = "16";
  reject(q);
  q = p;
  q["plan"]["fold_count"] = "16";
  reject(q);
  q = p;
  q["plan"]["groups"][1]["start_ns"] = "29";
  reject(q);
  q = p;
  q["plan"]["groups"][1]["id"] = "g0";
  reject(q);
  q = p;
  q["plan"]["groups"][0]["end_ns"] = "10";
  reject(q);
  q = p;
  q["purge_before_ns"] = "1000";
  reject(q);
  q = p;
  q["embargo_ns"] = "18446744073709551615";
  reject(q);
  q = p;
  q["purge_after_ns"] = "18446744073709551615";
  reject(q);
  reject(p, e::unix_time_ms() - 1);
  // Stable request for installed CLI/SDK boundary verification.
  q = p;
  q["output_path"] = path("installed-result.json");
  d::create_file(path("combinatorial-request.json"), q.dump(2), e::no_deadline);
  std::cout << "SBV combinatorial: " << checks << " assertions passed\n";
  if (!env)
    std::filesystem::remove_all(root);
  return 0;
} catch (const std::exception &x) {
  std::cerr << x.what() << '\n';
  return 1;
}
