// Test-only explicit caller-selected owner limits, copied from the adapter
// fixture.
J request(const std::string &root, const std::string &raw,
          const db::Metadata &m) {
  return {
      {"protocol", "symphony.sbv.source-retain-input.v1"},
      {"output_path", root + "/source.json"},
      {"source",
       {{"path", root + "/original.dbn"},
        {"expected_sha256", e::sha256_hex(raw)},
        {"dataset", m.dataset}}},
      {"capture_description",
       {{"source",
         {{"provider_ref", "databento"},
          {"interface_ref", "retained-local-DBN-file"},
          {"interface_version", "offline-import.v1"},
          {"operation", "offline-file-admission"},
          {"adapter_ref", "caller-declaration"},
          {"adapter_version", "caller-declaration"},
          {"dataset_id", m.dataset},
          {"dataset_revision", "provider-revision-unspecified"},
          {"selection_ref", "source-sha256:" + e::sha256_hex(raw)},
          {"native_schema_ref", db::native_schema},
          {"native_encoding_ref", db::encoding_for_version(m.version)},
          {"access_scope", "private:user-research"}}},
        {"attempt_id", "retained-adapter-fixture"},
        {"attribution_ref", "caller:SBV-offline-tests"},
        {"source_position", ""},
        {"coverage", "partial"},
        {"coverage_scope",
         "record-limited retained source; not a complete market interval"},
        {"coverage_evidence_ref", "native test declaration"},
        {"source_record_count", nullptr},
        {"times",
         J::array({{{"role", "acquisition"},
                    {"value", "2026-10-07T03:00:00Z"},
                    {"format_ref", "ISO8601"},
                    {"clock_ref", "fixture-declaration"},
                    {"precision_ref", "second"},
                    {"evidence_ref", "offline admission fixture time; not "
                                     "provider download time"}}})}}},
      {"access_evidence",
       {{"producer_ref", "caller:user-research"},
        {"evidence_ref", "retained source; no new authorization assertion"}}},
      {"owner_profile", "sqv-local-retained-capture.v1"},
      {"limits",
       {{"dbn",
         {{"max_file_bytes", "8388608"},
          {"max_metadata_bytes", "1048576"},
          {"max_records", "1048576"}}},
        {"capture",
         {{"max_capture_bytes", "8388608"},
          {"max_metadata_bytes", "16384"},
          {"max_field_bytes", "4096"}}},
        {"metadata",
         {{"max_manifest_bytes", "65536"},
          {"max_field_bytes", "4096"},
          {"max_evidence_refs", "128"}}},
        {"flow",
         {{"max_payload_bytes", "8388608"},
          {"max_frame_bytes", "8396800"},
          {"max_descriptor_bytes", "4096"},
          {"global_allocation_bytes", "67108864"},
          {"max_ports", "4"}}},
        {"store",
         {{"max_frame_bytes", "8396800"},
          {"max_store_bytes", "33554432"},
          {"max_batches", "4"}}}}},
      {"retention",
       {{"mode", "create"},
        {"root", root + "/store"},
        {"partition", "selected-partition"},
        {"producer_generation", "00000000000000000000000000000001"},
        {"store_generation", "00000000000000000000000000000002"},
        {"first_sequence", "7"},
        {"batch_sequence", "7"}}},
      {"extensions", J::object()}};
}
J feed(const std::string &path, const J &result) {
  return {{"reference",
           {{"path", path},
            {"expected_sha256", result.at("content_sha256")},
            {"pointer", "/sections/source/data"}}},
          {"delivery",
           {{"profile", "retained_before_delivery"},
            {"view_id", "selected-view"},
            {"recipient_id", "sbv-test-dataset"},
            {"recipient_interface", "symphony.sbv.dataset-feed.v1"},
            {"first_sequence", "7"},
            {"outstanding_byte_credit", "8388608"},
            {"max_unacknowledged_batches", "1"},
            {"processed_ack", "dataset_admitted"},
            {"checkpoint", nullptr}}}};
}
